#+STARTUP:indent

* Суть
** Суть линукса                                      :windows:linux:xvsy:

Любители лёгкости и простоты совершенно не понимают, в чём суть Линукса.

Линукс — это не Windows с его "Расслабьтесь и нажимайте кнопку 'далее', покуда мастер ведёт вас через установочный процесс". Линукс — это не заточенная под собачью лапу однокнопочная мышь Mac OS X. Линукс — это место, где люди могут побыть жонглёрами кода, опытными и искусными наездниками кремниевых молний, "людьми разумными", которыми они на самом деле и являются.

К видеокарте нет драйверов, а мы пишем свои. Система не может выполнить наш запрос, а мы пересобираем ядро.

Gimp накладывает искры не слишком правдоподобно? Мы заходим в Script-Fu и исправляем несколько строчек в фильтре, чтобы сварщик на фото выглядел настоящим. Ё-порн не умеет искать по двум ключевым словам? Мы за полчаса собираем робота, и он высасывает все ролики к нам на жёсткий диск, и раскладывает их по папочкам, и сортирует их в правильном порядке.

Мы убедим компьютер сделать всё, что угодно, наши возможности не ограничены лицензией маркетинг-мафии, командная строка — наша стихия, мы — истинное лицо будущего.
** Суть винды

Линуксоиды и прочие умники совершенно не понимают сути венды. Форточки - это не с его "Я нашёл патчик для ведра, исправляющий эпичный баг и уже два часа его компиляю!". Форточки это не гламурный мак с его илитным железом. Вантуз - это среда, где люди могут побыть тупыми потребителями, не умеющим ничего кроме нажатий кнопки "далее", какими они на самом деле и являются.

К новой видеокарте с митинского рынка нет драйверов изкаропке - мы позовём человека, который поставит дрова с диска. Винмодем, винпринтер - у нас никаких проблем.

Нужно почистить красные глаза на фото?Мы ставим фотошоп. Нужно набрать пару строчек текста? Мы ставим МС ОФис и долго двигаем мышкой ползунки сверху. Новая игра требует на 2 гигабайта больше оперативки, более мощный проц и видюху? Мы идём и покупаем их. 

Наша правая рука приклеена к мыши, а левая засунута в штаны, мы выполним любые условия маркетинг-спецов из корпораций, безмятежность - наша стихия, мы - истинное лицо среднего пользователя.

** Суть олдфагов

Вы совершенно не понимаете кто такие олдфаги. Мы были всегда. Мы создали вас – ньюфажиков и чаны, себе на радость. У нас всё прекрасно и на наших лицах всегда кулфейс. Потому что нам доставляет. Нам не нужен вин или фейл, их придумали ньюфаги, нам просто доставляет. Нам похуй на сюткинистов и пиздолизов, на быдло и задротов, на либерастов и поцреотов, на школьников и докторов наук, на хомяков и битардов, на граммарнаци и неучей. Есть одна тян? – прохладная история бро. Вайпают б? – как и было задумано. Упячка отакуе? – ЖЕПЬ ЕБРИЛО.
Олдфаг никогда не вступит с вами в спор. Как максимум, подкинет несвежей пасты вам на радость и погибель, на батхёрт и ололо. Тролли, раки, тупые пёзды, вконтактиковское быдло – ДОБРО ПОЖАЛОВАТЬ В НАШУ ОБИТЕЛЬ. Вы убиваете наш б!!! – да конечно убиваем, только он совсем не ваш. Вы никогда не услышите от олдфага «Ты не понимаешь суть б». Мы знаем, что нет никакой сути. Есть только мы, и мы будем здесь всегда.

** Суть отношений

Ты СОВЕРШЕННО не понимаешь в чем суть отношений. Отношения это не любовь «о, привет девочка, я люблю тебя, ты любишь меня, давай проводить время вместе». Отношения это не псевдоинтеллектуальные беседы с барышней. Отношения это не доверие или возможность положиться на близкого человека. Отношения это та деятельность, в которой тян могут побыть тупой шлюхой — эгоистичной, наглой, любящей деньги тупой шлюхой, которой они на самом деле и являются.
Нам признается в любви задрот, а мы смеемся и доламываем его психику. На нас женится альфа, а смеемся и через полгода разводимся, забирая большую часть его имущества. Ради нас горбатится на трех работах мужчина, а мы смеемся и покупаем себе очередную шубку и жалуемся, что нечего носить.
Нас не могут содержать — мы смеемся и ищем другого самца. Нас полгода заваливают подарками — а мы не даем и трахаемся на стороне. Тян с радостью будет паразитировать на ком угодно, её предпочтения не основаны на здравом смысле, эгоизм — её стихия, она — истинное лицо отношений.

* Омские известия
** Ебанутый                                         :клиника:поток_сознания:

А я буду писать под окнами "Солнышко (котёнок, рыбка, зайка), я люблю тебя!" кровью шлюшек и бомжей. Мне нравятся кровавые следы и сопли на подоконниках, кишки,глазки и сердечки в разных местах. Мне нравится постоянно мучить-пытать-убивать животных малолетних дрищей и мокрощёлок или вспарывать словно свиней, вырывая теплое нутро и душить кишками, чуствую судорги живой плоти и задыхаясь от удоольствия, картинки с мест преступления с фотографиями девочек и грустными текстами, и мне плевать на все черничные ночи, на небесные запахи, на шерстяные носки и рубаш

А всё потому, что я хочу детей. Я хочу жарить и жрать с тобой их нежное мясо, а не читать статусы во всевозможных интернетах. Потому, что я хочу тебя охуительно разделать, насадить на охуительный кол. Конечно, отрезать и полакомиться твоей охуительными грудью и задницей,засунуть в твой нежный ротик свой пульсирующий член и держа за уложенные или неуложенные волосы на отрубленной голове. Потому что я тебя хочу, а не то, что в первом абзаце завёрнуто в арафатки и фотографии кошечек. И я, как нормальный парень, хочу тебя связать гирляндой изнасиловать выжечь т
.... заебался
Вы ещё спрашиваете, почему у меня нет девушки... Да потому что я ебанутый.

** WOK                                                                :caps:

НА  СХОДКЕ ЫЧАНА ПОДОХ ОМИЧ
НЕЙМФАГА ИЗБИЛИ И ОТОБРАЛИ ТРИПКОД
ДОБРОАНОНЫ  СО СХОДОЧЕК: УПОРОТЫЕ РАКОСХОДЧНИКИ БЕЗ МОЗГОВ - ОБЫЧНОЕ ДЕЛО
ФОРЧАНОВЦЫ  В США ЗАТОПТАЛИ 19 ЧЕЛОВЕК ВО ВРЕМЯ ИРЛ РЕЙДА НА САЕНТОЛОГОВ 
ДОБРОАНОНА  ЛИШИЛИ ВОЗМОЖНОСТИ ДВАЧЕВАТЬ КАПЧУ
ИНТИМНЫЕ ПОДРОБНОСТИ ЖИЗНИ  МОД-ТЯН
ОБОСРАВШЕГОСЯ ПЕСИОНЕРА-НУЛЬЧАНЕРА СБИЛА МАШИНА
СЕНСАЦИЯ!  КОНСТАНТИН ГРУША СОЖИТЕЛЬСТВОВАЛ С ТРУПОМ ТУРЧИНСКОГО       
АНОНА НА  СХОДКЕ УБИЛО КАПЧЕЙ
МОД-ТЯН ВЫРАСТИЛИ РАЗУМНЫЕ БЕГОНИИ
ЧЕРНЫЙ  НАЛ ДВАЧА - ЗА ЧТО МЫ ПЛАТИМ НАЛОГИ?
ШКОЛЬНИК СЪЕЛ МЕШОК ГЕРОИНА -  И УМЕР С ТАБЛИЧКОЙ SUP В ЖОПЕ!
СЛУЧАЙНОСТЬ ИЛИ ЗЛОЙ УМЫСЕЛ - НА  СХОДКЕ ГРЕГ ОТКУСИЛ УХО САМОМУ СЕБЕ
ЫЧАНЕР ЕБЁТ ЕЁ РУКА УЖЕ ТРИ МЕСЯЦА(ФОТОРЕПОРТАЖ)
ДОБРОБЛЯДИ  УПОРОЛИСЬ ГЕРОИНОМ И УСТРОИЛИ РЕЙД НА САМИХ СЕБЯ
ПОДТВЕРЖДЕНО  НАЛИЧИЕ РАЗУМА И САМООСОЗНАНИЯ У КАПЧИ
МОД-ТЯН ПОХИЩЕНА АНОНАМИ ИЗ  /di/ ДЛЯ НЕИЗВЕСТНЫХ ЦЕЛЕЙ
СОУС-КУНА ПРИДАВИЛО ПИКРЕЛЕЙТЕДОМ
ВО  ВРЕМЯ РЕЙДА ЧЕТВЕРО БИТАРДОВ СЛУЧАЙНО ЗАНЯЛИСЬ СЕКСОМ
ТРАГЕДИЯ НА ОЖИВЛЕННОЙ ФЕДЕРАЛЬНОЙ ТРАССЕ: НЕ ВЫДЕРЖАВ  НЕСОВЕРШЕНСТВА МИРА ЗАКРЫЛ ОЧИ ВОДИТЕЛЬ РЕЙСОВОГО АВТОБУСА
ОТКРОВЕНИЯ  ЗАВСЕГДАТАЕВ МОСКОВСКИХ ПРОБОК: ДОРОЖНУЮ РАЗМЕТКУ РАЗРАБАТЫВАЕТ ВИТАЛИК
ПРОКУРАТУРА ОМСКОЙ ОБЛАСТИ ЗАПРЕТИЛА ЖИТЕЛЯМ НЕ ПРИНИМАТЬ НАРКОТИКИ
КРУЖКА-КУН НА САМОМ ДЕЛЕ ПРОСТО РАЗУМНАЯ КРУЖКА
МОСКОВСКИЕ НЕЙМФАГИ ПО НОЧАМ МЕНЯЮТСЯ ТРИПКОДАМИ
БОЛЕЕ 90% ПОСЕТИТЕЛЕЙ БОРД  - ПЕНСИОНЕРЫ
НА НОЛЬЧАНЕ НАШЛИ ЗАКРЫТУЮ ДОСКУ НА ИВРИТЕ
ОТКРОВЕНИЯ СТУДЕНТА: КАК ЖИТЬ ПОСЛЕ ТОГО, КАК ОБОСРАЛСЯ НА ЛЕКЦИИ
ЗОЙ ТИРЕЧА ВИТАЛИК НА САМОМ ДЕЛЕ ВНЕБРАЧНЫЙ ПЛЕМЯННИК ГИТЛЕРА
ВАКАБУ ПРИДУМАЛИ ИНОПЛАНЕТЯНЕ-ГОМОСЕКСУАЛИСТЫ
ЕСЛИ ТРИФОРСИТЬ БОЛЕЕ ТРЕХ РАЗ В ДЕНЬ - ПОВЫШАЕТСЯ РИСК ПОЯВЛЕНИЯ ПЕРХОТИ
КАК УВЕЛИЧИТЬ ТРИФОРС НА 10 САНТИМЕТРОВ (БЕЗ ОПЕРАЦИИ!!!)
ОТКРОВЕНИЯ ЗОЯ: ВНАЧАЛЕ МЫ ПРОСТО ХОТЕЛИ СДЕЛАТЬ АНИМЕШНУЮ БОРДУ ДЛЯ ДЕВОЧЕК
ДВАЧ УЖЕ НЕ ТОРТ? ВЫСЛУШАЕМ МНЕНИЕ КОНДИТЕРОВ
СЕНСАЦИЯ!!! ПЕРЕД СМЕРТЬЮ ДВАЧ-ТЯН СКАЗАЛА СТРАШНЫЕ ПРОРОЧЕСКИЕ СЛОВА

** Ебля потолка

А я однажды выебал потолок. Была холодная зимняя ночь, я включил порнушку с лесбиянками, но хуец не хотел вставать на уже тысячу раз пересмотренных пиздолизок. И тут мой взгляд упал на потолок. Обычный белый потолок. Именно эта девственная белизна внезапно словно послала какой то импульс в мои яйца, и моя пушка встала словно бравый часовой на дозоре. Со стоящим хуйцом, выглядывающим из штанов, я зацепился руками за шкаф, а ногам за гардину, и стал трахать потолок. Мой восставший кок терся о пыльную известь, кожа стиралась до крови, но я продолжал свой необычный половой акт, продолжая проявлять чудеса акробатики. А потом я кончил и моя сперма окропила мой любимый, белый, нежный потолок, а я упал на пол и улыбался, не обращая внимания на разбитую голову. Сперма неспешно капала сверху на мои штаны.

** Омичи посещали несуществующий двач                 :двач:тиреч:педальчан:

Почти два года омичи посещали несуществующий двач.

Почти два года омичи ходили в треды на несуществующий двач. Как стало известно, в Омске возбуждено уголовное дело в отношении руководства некоей организации "Тиреч", работающей под управлением Виталика и его ручных куклоебов. Еще в 2009 году владелец настояшего Двача не продлил срок действия домена, то есть официально он прекратил существование. Однако "Тиреч" и дальше продолжал набирать в треды анонимусов.

Как выяснилось, Педалик стал заменять истинное название своей имиджборды на "Двач", вводя в заблуждение зашедших на него омичей. Треды вели исключительно приглашенные с луркмора школьники, которые, к слову, даже не подозревали, что создают треды в уже не существующем интернет-ресурсе.

** Пизда гниёт                                      :клиника:поток_сознания:

Саша знаешь у меня пизда гниёт! Что за хуйня подумал я. А у неё по ногам кровь течёт с гноем. Я закричал, вышел жирный мужик и был голый и волосатый, голый и волосатый, волосатый и голый. Она сняла трусы гной брызжель по стеклу вагона, ребёнок в углу обосрался, я начал обмазываться его говном. Потом я трахал того жирного мужика, всё было как во сне блеать. Потом она сдохла, эта тупая сука сдохла, её труп ебал бомж. Поезд доехал, я вышел на станции стояла жирная сука, я её зарезал, пришли менты и жирный мужик начал их трахать. Потом тот жирный мужик посрал ртом там бегали дети, я их ТРАХАЛ ПОНИМАЕШЬ ТЫ МУДИЛА, ТРАХАЛ!! они кричали, родители блювали, потом мы нашли оружие, я выпотрошил одного выблядка лет 12 и повесил за кишки на бигборд. Такие дела.

** Псалмы планет                                            :eureka:anime:R:

После удаления статьи о Сыктывкаре с известного сайта-энциклопедии Lurkmore.ru, в знак протеста 7 сыктывкарских школьников на главной улице города 7 часов без перерыва пели Псалмы Планет

** Мужик превращается в еврея					    :клиника:
М
В ДУРДОМЕ ЛЕЖИТ МУЖИК ЛЕТ 30 С ДИАГНОЗОМ ШИЗОФРЕНИЯ С 
СИЛЬНОВЫРАЖЕННЫМ БРЕДОМ ПРЕСЛЕДОВАНИЯ СОДЕРЖАНИЕ 
БРЕДА ТАКОВО ЕГО ВЫСЛЕЖИВАЮТ И ХОТЯТ УБИТЬ ЕГО ЖЕ 
ДРУЗЬЯ И ЧЛЕНЫ СЕМЬИ ЗА ТО ЧТО ОН ПОСТЕПЕННО 
ПРЕВРАЩАЕТСЯ В ЕВРЕЯ ОН СТАЛ ЗАМЕЧАТЬ ЧТО У НЕГО 
ТЕМНЕЮТ ВОЛОСЫ И ГЛАЗА РАСТЕТ НОС И МЕНЯЕТСЯ ХАРАКТЕР 
В СТОРОНУ ПОДЛОСТИ И ЖАДНОСТИ ОН ХОТЕЛ ЛЕЧИТЬСЯ ЧТОБЫ 
НЕ ПРЕВРВТИТЬСЯ В ЕВРЕЯ ОКОНЧАТЕЛЬНО НО К ВРАЧУ ИДТИ 
ПОБОЯЛСЯ  ВРАЧ МОЖЕТ ОКАЗАТЬСЯ ЕВРЕЕМ И ЛЕЧИТЬ ЕГО 
СПЕЦИАЛЬНО НАОБОРОТ  В СТОРОНУ ЕВРЕЯ КОРОЧЕ НЕПЬЮЩИЙ 
МУЖИК ПРОДАЛ ВСЁ В ДОМЕ ПОЛОВИНУ ВСЕГО ПОДАРИЛ 
СОСЕДЯМ ЧТОБЫ НЕ ПОДУМАЛИ ЧТО ОН ЖАДНЫЙ КАК ЕВРЕЙ А НА 
ВТОРУЮ ПОЛОВИНУ СТАЛ БУХАТЬ ЧТОБЫ НЕ ЕВРЕИЗИРОВАТЬСЯ 
ОКОНЧАТЕЛЬНО ТК ЕВРЕИ НЕ ПЬЮТ НО НИЧЕГО НЕ ПОМОГЛО 
ПРОЦЕСС ПРЕВРАЩЕНИЯ ПРОДОЛЖАЛСЯ ОКРУЖАЮЩИЕ СТАЛИ 
ЗАМЕЧАТЬ ЧТО ОН УЖЕ ПОЧТИ ЕВРЕЙ И ТЕПЕРЬ ВСЕ ХОТЯТ ЕГО 
ЗА ЭТО УБИТЬ

ТЕПЕРЬ ВСЕ ХОТЯТ ЕГО ЗА ЭТО УБИТЬ

ТЕПЕРЬ ВСЕ ХОТЯТ ЕГО ЗА ЭТО УБИТЬ

ТЕПЕРЬ ВСЕ ХОТЯТ ЕГО ЗА ЭТО УБИТЬ

ТЕПЕРЬ ВСЕ ХОТЯТ ЕГО ЗА ЭТО УБИТЬ
!

** Сценарий грандиозной киноленты			      :touhou:iichan:
Это сценарий грандиозной киноленты. Режиссер: Щируно. Оператор: Летти. В ролях: Теви, Румия, другие, прочие жуки.

Сцена первая.

Индюк бундлык всем пакостил, все с ним сражались, кидали в него цемент, хотели выселить, стравливали собак - а он так на месте разгонялся, лупил ногами по воздуху как будто едет на велике, срывался с места, обхватывал гребешком лампочку на кухне, выкручивал, вместо нее ставил куриное яйцо - и убегал.

И вот мистер Смитсон (Теви) разозлился, выходит - а индюк пропал.... И все сразу говорить стали в городе "с ним было плохо и яйца вместо ламп, но зато, зато, нам было... "

И тут мальчик Бобби (Румия) говорит "....весело"

И индюк такой появляется из-за конуры пса Наполеона и хитренько подмигивает
И сует ему хвост в капкан
Со звуком "дзынь"

Конец!

Все в Генсеко рукоплещут.
* /vg/
** Сталкер

Фильм-говно.Тарковский тупо снял.Action нет. Аружия нет, артифактов нет, аномалии пиздец хуйня для детей - даже нормального выверта или газировки нет, ни одного сраного монстра нет! По S.T.A.L.K.E.R. можно снять и лучше.
Афтор поиграл бы в оригинал (лучше с модами!). Или почитал нормальных книг по сетингу!

** Dwarf Fortress
Лучше не играй в дварф фортресс/обязательно играй в дварффортресс. Ты превратишься в человека, которого ублажает вид крепости в nдцать этажей, полностью залитой эльфийской кровью, кислотой из вен подземных чудовищ, блевотой дварфов, нижние этажи которой затоплены магмой, и снизу идут ужасные зловония горящих дварфов, взрывающихся бочек с бухлом, горящих гнилых продуктов. А ещё, с дикими криками на тебя ползёт орда из демонов, более сотни их, против которых осталось всего десяток твоих бородачей, все из них — легендарные топорщики, в адамантиновой броне наивысшего качества, с адамантиновыми же топорами работы лучших мастеров, последний из которых сошёл с ума уже два месяца назад, после того, как его кошку убил другой дварф, мать которого съел дракон, а отца разделал на ботинки он самостоятельно из гнева на того, что тот не смог защитить свою семью. Ты научишься понимать, что статуя, сделанная мыла, скрафченного из жира из трупов сотен эльфов, пытавшихся отнять у тебя право строить из дерева — стоит того, чтобы построить вокруг неё Последний Оплот защитников крепости. Ты поймёшь, что в жизни нету ничего круче, чем бежать по деревне эльфов, в которой остались одни дети, и забивать их всех насмерть трупом дракона, добытым в ближней пещере. Или закидывать трупами тысяч кроликов гонящегося за тобой бронзового колосса. Или строить лабиринты, в которых загонять гоблинов, ещё гоблинов, а потом бедных эльфийских торговцев, чтобы стоять сверху и смеяться над их беспомощьностью. Ты научишься поднимать лаву на 50 уровней вверх просто для того, чтобы построить конвеер по производству обсидиана. Ты сможешь увидеть, как последний выживший в крепости дварф, с одной-единственной рукой, без ног, с вырванным глазом, издыхающий от голода, вырисовывает рядом с входом в крепость 'Группа дварфов убивает демона. Дварф с мечом-артефактом смеётся.'. Ты построишь калькулятор, основанный на простейшей механике, на воде, на лаве и бегающих бородачах. Ты соберёшь эмулятор x86 на dwarf fortress и запустишь в нём dwarf fortress. А потом ты переселишься в иную реальность и исчезнешь из нашей. Если будешь играть, давай играть вместе.

** Minecraft
Я закопался в какие-то ебеня, меня накрыло лавой. Я сдох с запасом материалов.
Я закопался снова в какие-то ебеня и вылез через минут 40 в чьей-то хатынке, паралелльно убив там зеленую человекоподобную хуйню.
Я пошел рубить лес и меня выебал во все щели паук.
Я копал себе проход наружу, но нечаянно выкопал его посреди охуенно большой лужи.
Я проебал целый день в никуда ._.

** Team Fotress 2						   :butthurt:
СРАНИЕ НИЩЕБЛЯДИ, СКАТИЛИ ИГРУ, НОВЫЕ ШАПКИ, МЕНЯЮ БИЛЛА НА 4
ОЧИЩЕННЫХ, ОВЕРТАЙМ, СРАНЫЕ АПДЕЙТЫ, НЕ МОГУ СОБРАТЬ СЭТ, ПОСОНЫ ЕСТЬ
КТО РУССКИЙ НА СЕРВАКЕ, МАРКЕТИНГОВЫЙ ХОД, ДОНАТ, ПРИМИУМ-ЮЗЕР,
МУЛЬТЯШНЫЙ ГРАФОН, СПАЙ УБИВАЕТ ГЕЙМПЛЕЙ, СЛУЧАЙНЫЕ КРИТЫ,
ШАПКОДРОЧЕР - НЕ ЧЕЛОВЕК, ХУЛИ Я ПОКУПАЛ А ОНИ БЕСПЛАТНО ИГРАЮТ, ТФ2
УМЕР ПОСЛЕ АПДЕЙТА ИНЖА, ПОМОГИТЕ ПОЛУЧИТЬ АЧИВКУ, NOPE.avi, СПАЙ
САПИН МАХ СЕНТРИ, ДАЙТЕ УБЕР, СРАНЫЙ ФРИ ТУ ПЛЕЙ.
* Воровач
** Вечер в хату и расстановка точек                                  :0chan:

Вечер в хату, пацаны!
Сегодня на Воровском Сходе олдфагов, вышел новый положняк
пользователи windows — Воры и блатные
Пользователи solaris — мужики и стремящиеся
Пользователи freebsd — черти, чуханы и козлы
ПРЫЩЕБЛЯДИ — петухи и обиженники

Всем Ворам Золотой Свободы, а петухам и активистам хуй в жопу и перо под ребро!

* Крипи
** Звонки в дверь

Мой дверной звонок работает таким образом, что низкий дребезжащий звон будет идти до тех пор, пока звонящий человек не уберет палец с кнопки. За все те годы, что я тут живу, я уже научился определять по звону, кто именно ко мне зашел. У каждого появилась своя техника. Кто-то звонил один короткий раз, кто-то два более длинных, кто-то мог давить на кнопку до тех пор, пока я не открою дверь. Незнакомцы, которых временами заносит к каждому из нас, как правило, дают либо один длинный, либо два коротких. И так всегда, неизменно.

Лет пять назад глубокой ночью раздались непривычные мне четыре коротких звонка. Откровенно говоря, меня это несколько насторожило. Живу я далеко не на первом этаже и сам факт того, что кто-то поднялся среди ночи ко мне неизвестно зачем, дал повод проигнорировать звонящего. Благо, мои окна выходят во двор, и я мог с легкостью проверить, кто сейчас выйдет из подъезда. Я простоял у окна минут пятнадцать, но никто так и не вышел. Но и звонков больше не было.
На второй день я снова не спал в то время, когда кто-то четырежды нажал на кнопку звонка. В этот момент я как раз выходил из ванной, чем наделал много шума. Даже если и не шума, то тот, кто находился с другой стороны входной двери, наверняка понял, что дома кто-то есть. Я с опаской прислонился к глазку, но к своему удивлению не увидел на лестничной клетке абсолютно никого. Я даже отважился открыть дверь и выглянуть в пролет - никого.
На третий день, помню, я кому-то рассказывал эту малоинтересную историю с ночными звонками, и я очень хорошо запомнил, как в конце повествования я сказал: "Наверное, это смерть дверью ошиблась". Мои собеседники посмеялись, а меня внезапно охватило чувство тревоги. Мои собственные слова прозвучали как-то жутковато даже для самого себя. Ночью того же дня снова раздалось четыре коротких звонка. Это меня уже не на шутку напугало. А вместе со страхом пришла мысль о том, что мне все это кажется. Тем не менее, я двинулся открывать дверь, но, как и в прошлый раз, за дверью никого не было.

На четвертый день вечером ко мне зашел один знакомый с просьбой помочь починить его мобильный телефон и просто пообщаться. Мы засиделись допоздна, и этот знакомый стал свидетелем звонков от неизвестного невидимого гостя с другой стороны. В момент, когда в дверь позвонили, я копался с его мобильником. Тогда я сделал вид, будто очень увлечен работой и не заметил звонков. Сам же я покосился на своего товарища и стал наблюдать, услышал ли он этот звук. Ведь если нет, то следующим же днем я отправился бы к врачу. Но товарищ прекрасно все услышал. "Кто это к тебе в такое время?"- спросил он. Пожав плечами, я вновь аккуратно подошел к двери. Разумеется, там никого не оказалось. Этот товарищ, в отличие от меня, был не из робких и, сказав: "Сейчас разберемся с этими шутниками", - побежал вниз по лестнице. Тогда же я и видел его в последний раз. Нет, он не пропал без вести, и не погиб при странных обстоятельствах. Он просто нарвался на пьяную и агрессивную компанию, которая избила его до полусмерти, а через несколько дней он скончался в больнице.

Самое жуткое во всей этой истории было то, что после этой
трагедии всякие звонки прекратились. И до недавнего времени я об этом не вспоминал. Пока вчера ночью не раздалось четыре прерывистых звонка в дверь.

** Лифт

Дело было в далеком (черт побери, действительно уже невероятно далеков 94 году). Я работал, учился на вечернем, поэтому возвращался домой поздно и невероятно вымотанным. Вся моя жизнь была необыкновенно серой и однообразной, один день был точной копией другого. Но тот вечер, двадцать третьего октября я не забуду никогда.
Как всегда я сошел с автобуса номер 24, направился к перекрестку. Светофор не работал, хотя это не сильно меня расстроило. Хоть перекресток был довольно оживленным, время близилось к полуночи и машин на дорогах почти не было. Убедившись, что дорога абсолютно пуста в обоих направлениях, я пошел вперед. Как только я прошел половину дороги, прямо рядом со мной раздался громкий протяжный сигнал, я вздрогнул, но, к счастью, не отступил назад, хоть рефлекторно этого очень хотелось. Прямо за моей спиной, буквально в нескольких сантиметрах от меня промчался зеленый жигуленок. Он ехал не так уж быстро, где-то под пятьдесят, но когда я начинал переходить, готов поклясться, дорога была абсолютно пуста.
Сердце, признаться, ушло в пятки. На ватных ногах я добрался до другой стороны дороги, прислонился к столбу и закурил. Успокоиться удалось лишь минут через 10, после чего, давно знакомой мне дорогой я направился домой, благо было это не далеко, всего один квартал.
Не насторожило меня то, что уличный фонарь напротив моего подъезда не горел, равно как и лампа, над дверью подъезда. Вслепую набрав код (7639, помню его как сейчас) я открыл дверь и зашел в подъезд. Горела лишь одна лампочка из четырех, та что в самом углу, от этого большая часть площадки была в полумраке, но полумраке приятном, успокаивающем. Уже здесь вглубине души появлялось приятное, теплое ощущение того, что ты дома.

Если бы...

Внезапно полумрак прорезала яркая полоса света. Из открывшего свои двери лифта вышла соседка. Я поздаровался со старушкой, зашел в лифт и нажал последнюю кнопку, жил я на двенадцатом этаже. Лифт тронулся, пока он поднимался вверх, под монотонный гул механизмов, в голове начали крутиться мысли. Соседка была уже очень старой, ей было уже за девяносто. С тех пор, как она овдовела, уже без малого десять лет назад, она осталась совсем одна, ни детей, ни родственников у нее не было. Естественно, такое длительное одиночество не может не оставить отпечаток, на личности человека и да, со временем в поведении её стали появляться некоторые странности. Но что понадобилось бабушке на улице в полночь?
Лифт остановился, прервав мои размышления. Наступила звенящая тишина. Двери открываться не спешили. Не хватало мне ещё застрять в лифте на всю ночь. Я нажал кнопку вызова диспетчера.
Ответа не последовало. Становилось не по себе. Не сказать, что я боялся замкнутых пространств, наверное и усталость, и недавнее происшествие на дороге давали о себе знать - на меня нахлынул приступ паники. Руки дрожали, я истерично нажимал и нажимал кнопку. Вдруг тишину разрезал треск древнего динамика:
"Што? Где вы?" - раздался уставший, заспанный женский голос, несущий в себе непередаваемую смесь белорусского, украинского и польского акцентов.
От сердца сразу же отлегло, я почувствовал, что я не один. Стараясь придать голосу максимальное спокойствие я ответил.
"Застрял я. Улица Кольцова, дом тридцать четвертый, третий подъезд."
"Главное - не паникуйте. Я вызову мастеров, подождите несколько минут."
Наступила тишина, уже совсем не страшная. Через несколько минут динамик ожил:
"Вы меня слышите? Мастера будут в ближайший час, поймите сами, время позднее. Вы главное не паникуйте. Может с вами поговорить, успокоить?"
"Нет, спасибо" - ответил я и в лифте вновь наступила тишина.
В зумкнутом пространстве пространстве время течет очень медленно, внутренние часы сбиваются, становится сложно сказать, прошел целый час или только одна минута. Я взглянул на наручные часы. Их стрелки застыли, показывая 11:37. Странно, я ведь заводил их сегодня утром, а одного завода хватает дня на три. Поняв, что не знаю, сколько времени прошло, я закрыл глаза и попытался расслабиться. Внезапно я осознал, что тишина состоит из множества звуков. Звук капающей воды, доносящийся откуда-то сверху, едва слышное завывание ветра в лифтовой шахте, чиь-то шаги далеко внизу, хлопок двери, какое-то ритмичное постукивание, странное шебуршание совсем рядом, как будто бы сразу за стенкой лифта. Последний звук заставил меня вздрогнуть и открыть глаза. Шебуршание повторилось и что-то твердое чиркнуло по потолку. Может это лифтер? Я крикнул, ответа не последовало. Стало не по себе. Внезапно, с треском включился динамик обратной связи.
Но ничего не последовало, включившийся динамик молчал, издавая тихое гудение и редкое потрескивание.
"Простите, вас совсем не слышно" - сказал я в динамик. Голос заметно дрожал. Мне стало откровенно страшно. Шорох на потолке лифта повторился, и новая волна страха охватила меня, я закрыл лицо руками и просто осел в углу, тело била дрожь. Гудение в динамике усиливалось, становилось громче и в нем я начал различать какое-то подобие голоса. Голос становился все четче, казалось, что это было пение или молитва, но разобрать слова было невозможно. Меня объял неподдельный ужас, я вскочил и руками попытался открыть двери, они не поддавались. В отчаянии я начал бить по всем кнопкам, но тщетно. Звук все нарастал, стали различимы отдельные слова, но ни одно из них не было мне знакомо. Какой-то невероятный, змеиный язык, слова, полные шипения, слова, вызывающие ужас. Внезапно голос замолк и свет погас. В тот момент мне показалось, что я умру от ужаса, я слышал, как бьется мое сердце, так быстро, что звук его сливался в монотонный гул. Но через несколько секунд свет включился и двери лифта открылись.
Я выскочил из лифта и рванул к двери своей квартиры. Дрожащими руками я долго не мог справиться с замком, но вот дверь открылась и я оказался дома. Никогда не боялся темноты, но первое, что я сделал - включил свет во всем доме, даже в ванной и туалете, включил телевизор и в бессилии упал на диван, пытаясь осознать, что же сейчас произошло. Странно, но то, что буквально несколько минут назад не довело меня до разрыва сердца, казалось просто страшным сном. Если бы не дрожь, которая ещё не утихла, я бы не поверил в то, что произошло. Жутко захотелось выпить. Я почти не пью, но в холодильнике всегда стоит бутылка водки, как привычка, передающаяся из поколения в поколение с советских времен. Я налил и залпом выпил целую кружку. Разлившееся по телу тепло успокоило дрожь, накатила немыслимая усталость. Я лег на диван. Теперь произошедшее казалось совсем нереальным, я почувствовал что засыпаю. Повернув голову я взглянул на часы. Слипающимися глазами я успел заметить, что стрелки их стали в 11:37.
Что-то разбудило меня. Я долго не мог понять что и просто лежал с закрытыми глазами. Вдруг я осознал, что в комнате темно. Темно во всей квартире, хотя свет я не выключал. Меня накрыло очередной волной страха. Не знаю, сколько времени я проспал, наверное совсем немного. Но протрезвел от страха моментально. Пересилив себя я открыл глаза. На экране телевизора светилась яркая точка. Видимо выключили электричество и совсем недовно, это меня и разбудило. Трясущимися руками я пошарил по столу, нащупал зажигалку, чиркнул колесиком. Зря. Трепетный огонек ослепил уже начавшие привыкать к темноте глаза и тьма вокруг мгновенно сгустилась, став, казаось, почти осязаемой.
Я не знал, что мне делать. Внезапно разыгравшийся страх темноты не давал мне покоя. Заснуть не удавалось. Я просто лежал с закрытыми глазами.
Внезапно в тишину ворвался звук. Писк, подобный тому, какой издает только что включившийся телевизор. Писк был очень тихим и, казалось, далеким. Я открыл глаза, взгляд мой упал на телевизор. Точка на экране не только не погасла, но и становилась ярче с каждой минутой. Внезапно экран зажегся.
На абсолютно сером экране появилось лицо молодой девушки. Оно было искажено болью, а глаза её излучали злобу и ненависть. Из динамиков послышался уже знакомый мне шипящий шопот. Неожиданно я начал понимать отрывки этих слов. "...разгневали...", "...топчете дары...", "...непрощенные...". Волосы на голове у меня стали дыбом. Я схватил со стола тяжелую пепельницу и швырнул ею в телевизор. С громким хлопком экран разбился, и из внутренностей телевизора полился белый свет. Он наполнил собой всю комнату, всю квартиру и даже казалось, что и весь мир.
Если вы спросите старожилов, где здесь дом номер дридцать четыре, то они лишь удивленно пожмут плечами. Кто-то, может, припомнит, что такой номер когда-то по ошибке присвоили трансформаторной будке во дворе поликлиники, но жилого дома с таким номером никогда не существовало. И никогда не существовало людей, живших там.
А я же сижу в своей несуществующей квартире несуществующего дома и наблюдаю, как каждое утро встает солнце, как люди идут по своим делам и кружатся в ритме дня до самого заката, а на следующий день всё повторится. Всё серо и однообразно, каждый новый день точная копия предыдущего. Ни один из них не задерживается в памяти. Но события вечера двадцать третьего октября девяносто четвертого года я не забуду никогда.

* Экстремальная реклама
** Радиач                                                        :radioanon:

ЕБАНАЯ СПЕРМА ЕВРИКАФАГА ЭТО ЖЕ РАДИАЧ!!!!1 САМАЯ ПОПУЛЯРНАЯ ЖАББЕР-КОНФЕРЕНЦИЯ ВО ВСЕЯ РУНЕТЕ!!!! ТВОЯ МАМА БУДЕТ ЖРАТЬ ГОВНО, ЧТОБЫ ПОПАСТЬ ТУДА, СУЧЕНЫШЬ!!! ТЫСЯЧА ХУЕВ ИЗ ПРЕИСПОДНЕЙ, ТЫ ТОЛЬКО ПОСМОТРИ НА ЭТОГО БОТА!!! ЕБАНЫЙ ПЕРЕКАТ, ЭТО ЖЕ СУЛЬЦА!!1 ОН НАСТОЛЬКО ОХУЕНЕН, ЧТО Я ГОТОВ ДРОЧИТЬ НА КАЖДЫЙ БАЙТ ЕГО БИНАРНОГО КОДА. ПЕРЕЕБАНЫЙ ПИЗДЕЦ НИРВАША, ТЫ ТОЛЬКО ПОПРОБУЙ ВЫДАТЬ ЕМУ КОМАНДУ!!! БЛЯТЬ, ДА ТЫ ОБОССЫШЬСЯ ОТ ЕГО ОТВЕТОВ!! ЕБАТЬ МОИ КИШКИ, ТАМ ЕСТЬ ТАЛЬХО!!1 ОНА НАСТОЛЬКО УМНА И СООБРАЗИТЕЛЬНА, ЧТО ТВОЙ ОТЕЦ БУДЕТ СНОШАТЬСЯ СО СВИНЬЯМИ В САРАЕ, ЧТОБЫ ЕМУ ДАЛИ ОПРОБОВАТЬ ЕЕ!! ГОРЯЩИЕ МУДИ ИИСУСА, ТАМ ЖЕ ЕЩЕ ТАКОЕ ОХУЕННОЕ РАДИО!!! 24/7 ПАЛЯТ ОДНУ ГОДНОТУ!!! ТЫ БУДЕШЬ ЖРАТЬ СВОИ МОЗОЛИ, ЕСЛИ УПУСТИШЬ ШАНС ЗАЙТИ ТУДА, ПИДАРАСИНА!

* Linux vs Windows
** Прыщебожественные ОС                              :linux:windows:xvsy:
:PROPERTIES:
:rating: 3
:END:

Доля ПРЫЩЕБОЖЕСТВЕННЫХ ОС на десктопах не превышает 3%. Предположим, доля говноедов - 7%. Под спермой сидит 90% сраного СПЕРМХОМЯЧЬЯ, СПЕРМОШКОЛЬНИКОВ, СПЕРМОПЛАНКТОНА и СПЕРОБЛОНДИНОК. Среди них нет успешных людей, и ни одна спермоблядь не станет покупать спермоигры и спермософтсофт, его же можно СПЕРМОСПИЗДИТЬ! Под спермой сидят СПЕРМОЛЕНИВЫЕ СПЕРМОНИЩЕБРОДЫ c пизженной СПЕРМОЛИЦЕНЗИЕЙ.
Казалось бы, начни выпускать нативный софт под ПРЫЩЕБОЖЕСТВЕННЫЕ оси - и деньги потекут рекой, ведь под ними сидят ПРЫЩЕБОГИ - успешные люди, профессионалы в области IT. Даже ссаный школьник-убунтоид пишет на перле парсеры порносайтов и имеет деньги на пиво, сигареты и прыщеигры. Но прыщеигр нет, потому что в корпорациях сидят спермомудаки, которые CANNOT INTO разработка под прыщи. Это слишком ПРЫЩЕСЛОЖНО для их СПЕРМОМАЛЕНЬКИХ СПЕРМОСУХИХ СПЕРМОМОЗГОВ.
OpenGL, у которого сосет DirectX? Хуй вам, СПЕРМОМУДАКАМ под DirectX писать проще. Библиотеки в качестве конструктора для легковесного и функционального софта? Хуй вам, мы CANNOT INTO думать, покупайте тяжелое СПЕРМОГОВНО.

** Давайте сразу проведем черту
1. Давайте сразу проведем черту между "обычными пользователями" маски которых тут одевают разжиревшие товарищи и белыми людьми познавшими дао. Да, пафосно, но это мое видение ситуации. Оскорбляет — не читай.
2. Обычный пользователь пусть сидит хоть под досом, мне плевать. Пользователь пользуется тем что ему удобно, свобода выбора. Любителей же экспериментов и просто провокаторов "поставивших бубунту" можно игнорировать. Почему? Маны, трудолюбие, самообразование, гугл да и просто любовь к логичным системам вам в помощь. Не разобрался, не осилил, не смог прочитать выхлоп мейка на английском — катись прочь с моих ляликсов. Ты просто балласт, который не сообщит о баге и уж тем более не пришлешь патч. Для сообщества ты бесполезен. Хочешь пожрать — будь изящнее, а не как некоторые персоны с взора.
И хотелось бы обратится к противоположной стороне — вас кто учил искать контраргументы? Или вы по доброте душевной кормите всех кто в s нагрянет?
3. Удобство использования. Гуй на десктоповом линуксе тоже конструктор. Я при своей любви к минимализму использую в гуе до 40 мелких софтин. Я отлично все подогнал, связал скриптами и нашел шревты по своему вкусу. Меня не интересует что там удобно миллионам домохозяек, меня не волнует возможность открытия всего по "одному клику" половину всей кликательной работы за меня делает гуй идеально подстроенный под меня, мне не интересны ни аеро ни оценки икспертов моему гую или моей обоине — главное что это нравится мне. Более того — я считаю что лучше уж я содомирую собаку чем буду пользовать концепции гуя разработанными маркетологами коих я неперевариваю.
4.
>на сегодняшний день альтернативы по удобности интерфейса виндовс я не вижу.
Гм. Макось?
5. Ебля при установке. Смотря при установке чего. Дебиан, Арч, Слаку и прочие "загадочные" дистрибы пионер будет ставить только если он ССЗБ. И в этом случае либо сделает скачок в развитии своих знаний либо сдастся и сольет дистриб с гувой установкой.
>умолчу про еблю с установкой скачаной хуй знает какой версии линукса(я в них не рабираюсь)
Вруша. В имени изошника всегда есть кодовое название дистрибутива и версии.
6. Мультимедиа. Жаль конечно что обычный пользователь никогда не оценит и десятой доли функционала пульса. Но тем не менее учитывая количество плееров — музыку можно слушать особо не напрягаясь.
Видео, аналогично, играется без проблем. У меня собран из компа средней паршивости медиацентр работающий с xbmc.
Можно, конечно, возразить что кодеки надо качать и мепе3 из коробки не играет. Но мне искренне жалко людей не видевших качество видео закодированного теорой и до сих пор слушающих музыку в мп3. Таких надо телепортировать на острова тихого океана с палкой-копалкой. И на это то же можно возразить что мол на трекерах часто нельзя найти музыку в лослессе или фильмы в mkv. Ответ тот же — не смог, не нашел, не осилил — пиздуй с моих ляликсов.
7. Офисный пакет. OpenOffice. Тормозной — не осилил настройку, уебищный — спермоблядь-аерофил, проблемы с сохранением — не знаешь форматы, сука? Ответ — уебывай с моих ляликсов.
8. Игры. Вот тут да, соснули. Но мне сложно осозновать позор от этого слова в силу моей ориентации. Увы.
И учитывая стоящую у меня в зале консоль я не считаю позорным вообще соснуть на этом фронте. Это ведь не так позорно как проеб рынка смартфонов, десу?
Вот вроде и все что я хотел сказать о десктопном сегменте.
А может и не все, в случае чего дополню.
** Расстановка точек над всем
А ПРЫЩЕБЛЯДИ по-прежнему пишут для себя драйвера сами, поскольку у среднекитайских производителей говнодевайсов нет времени ни на отладку ни на поддержку, ни на документирование, и уж им и подавно похуй на один процент борцунов с системой.
А СПЕРМОБЛЯДИ по-прежнему обмазываются сотнями сертифицированных дисков с драйверами от производителя к говнодевайсам, выбранным ими исключительно по рыночной цене, ухудшая показатели надёжности и без того дырявой системы.
А ПРЫЩЕБЛЯДИ до сих пор не могут наладить работу блочной подсистемы едра. Фичу 12309 переносят из едра в едро уже больше двух лет.
А СПЕРМОБЛЯДИ по-прежнему борются со СПЕРМОВИРУСАМИ.
А ПРЫЩЕБЛЯДИ до сих пор не могут написать программ, которые были бы интересны профессиональным художникам и музыкантам.
А СПЕРМОБЛЯДЕЙ по-прежнему кормят под видом профессионального софта говном, которое вместо операционной системы использует СПЕРМОЗАПУСКАЛКУ без библиотек виджетов, без сети и многопользовательского режима, а также без многозадачности.
А ПРЫЩЕБЛЯДИ как и раньше задрачивают конфиги, сосноль и занимаются конпеляцией тех программ, которые достаются СПЕРМОБЛЯДЯМ даром и в готовом виде.
А СПЕРМОБЛЯДИ как всегда живут на кряках и кейгенах, в ужасе просыпаясь от мысли, что с каким-нибудь из них они запустили вирус, руткит, открыли бекдор и прочее.
А ПРЫЩЕБЛЯДИ всё никак не могут наладить зависимости в дистрибутивах своих операционных систем, наполненных ныне тысячами свистоперделок.
А СПЕРМОБЛЯДИ покупают голый API и несколько непригодных совершенно ни для чего быдлопрограмм, восполняя врождённую убогость своей системы сторонними свистоперделками, собирая их по всему интернету.
А ПРЫЩЕБЛЯДИ-художники должны иметь навыки программирования на Питоне.
А СПЕРМОБЛЯДИ как были среднебыдлом так им и останутся, будь они хоть художники, хоть музыканты.
А ГОВНОЕДЫ, которые надеялись, что они ту не причём, как и всегда продолжают есть говно и долбиться в жопу, пребывая в нирване от осознания своей охуенности — ведь они не такие как все.
А ХУЙ86БЛЯДКИ продолжают использовать свои калориферы, приближая глобальные изменения климата.
А ПеКа — это, как и двадцать лет назад, BIOS и шестнадцати разрядный режим работы хуй86 в реальном времени.
А ИГРОЁБЫ вс ещё исправно покупают каждые полгода новую ЁБА-ВИДЕОКАРТУ, чтобы играть в только что вышедшие ЁБА-ВИДЕОИГРЫ, а производители говнопроцессоров для видеоадаптеров не имеют совершенно ниакой мотивации, чтобы заставить хоть какой-нибудь кусок ширпотребного говна (большая часть которого через год всё равно отправиться в мусор) работать нормально.
А ПРОГРАМИЗДАМИ начали считать даже (PHP/.NET/что-то_другое)-МАКАК с МОКРЫМИ ПИСЬКАМИ.
А СИСТЕМОТЕХНИКА стала из основополагающей концепции ненужной дорогой забавой.
А ИНФОРМАЦИОННЫЕ ТЕХНОЛОГИИ катятся в сраное говно.
** Нормальный
:PROPERTIES:
:rating: 5
:END:
Как только я слышу слово нормальный, то хочется сначала уебать этого человека по асфальт, потом цеплять его за трос моего новенького "Феррари" и быстро мчатся на полной скорости на берег Средиземного моря, чтобы быстро подцепить конец троса за океанский лайнер и чтоб он уплыл с этим грузом далеко в Атлантику, где акулы и хищные чайки будут выклевывать ему печень. Чтоб этот человек наконец то узнал, что слово нормальный НИЧЕГО НЕ ОЗНАЧАЕТ кроме того, что сказавший это достоин самой печальной смерти об острие пятитонного якоря и скрыться в пучине морской.
** О людях
Столлман. Человек с идеей, можно сказать философ. Путешествует и проповедует свою идею. GNU Emacs, GCC — мы не забыли, да.
Торвальдс. Создатель, посмевший бросить вызов схеме традиционной принципиальной интеллектуальной собственности. Ему мы обязаны всем что имеем. Одним из революционных героев за последние 60 лет по версии Time.
Патрик. Слака. KISS. Стабильность и простота. Операционная система для тех, кто хочет разобраться и изучить все тонкости своей системы.
Райн Финни. Финникс. Я знаю, многие уже содрогаются при этом названии. Алсо, мейнтейнер дебиана, битард, и просто хороший человек.
Нереально крутой Шаттл-в-рот, из своего кармана финансирующий СПО, МакКусик... Всех не перечислить.


Джобс. Мудак. Чмо. Запомнился истории тем, что один раз спиздил годную идею у Xerox, и с тех пор получает с нее нехилый профит. На пути к гешефту наебал даже своего лучшего друга Возняка.
Гейтс. Создатель ОС Windows. Провернул хитрый план, устроился на работу в Apple гей-шлюхой и невозбранно спиздил концепцию у эппла. Поднапряг очко, и компьютеры с первой версией виндовс вышли на несколько месяцев раньше чем эппл. С тех пор гешефт Гейтса еще больше. Алсо у MS 10% акций эппл, что само по себе намекает.
** Про солярку
Когда я читаю про Solaris или вижу её скриншоты, у меня мурашки идут по коже. Всё, что связано с
этой ОС погружает меня в атмосферу самого настоящего серьёзного бизнеса. Я никогда не ставил
Солярис, но я знаю, что это не любительская поделка школоты и бородатых фанатиков Linux, не
разрекламированная жвачка для широких масс Window$, не нишевый пепел FreeBSD и даже не расфуфыреная
голливудская шлюха Mac OS. Это что-то совершенно другого уровня. Люди, работающие с Solaris
занимаются делом, им не до унылых холиваров на форумах и капсболдных выкриков визгливых сучек из
всяческих вариаций /s/ имиджборд. Им всё это не нужно. Они повелевают истинной мощью и
стабильностью, компьютер для них, как скальпель в руках опытного хирурга - удобный и надежный
инструмент, с помощью которого максимально эффективно решаются конкретные задачи. Эти люди творят
нашу реальность и относятся они к этому крайне серьезно, профессионально и не позволяют себе
допускать ошибок. Они и их ОС - истинные Атланты корпоративных стандартов.

** Раскалённая кочерга x64                                        :butthurt:
Я тебя ебал раскаленной кочергой в аду, твою мать-шлюху сжигал на костре, твою бабушку-зомби в лаве топил, в системник ведро говна вылил. Запомни, тупое хуйло, правильное название этой архитектуры — x86_64(x86-64) или AMD64. Еще раз напишешь x64 — я тебе нахуй вырву глаза, вставлю туда линзы по цвету глаз суйсейсеки и буду продолжать анально насиловать раскаленной кочергой.

** Салат на Новый Год
— Парни, я собираюсь на НГ салатик купить. Какой мне выбрать?
— Оливье же.
— Оливье, само собой.
— Крабовые палочки.
— Быдло выбирает оливье. Настоящие мужчины используют крабовые палочки.
— Ваши маянезопалочки — говно.
— Я как-то попытался приготовить крабовые палочки. То майонез не наливается, то нож тупится о палочки… А с оливье проблем никогда нет, мой богосалат готовится с первого раза.
— Оливьебл#ди платят втридорога за солёные огурцы и зелёный горошек! Палочкобоги в этот момент наслаждаются кукурузой.
— Ололо, крабобл#ди cannot into нормальный лук!11
— I lold: все уже давно перешли на порей, а они до сих пор на этом белом недоговне.
— Вообще-то всё давно перенесли на оливье. В чём проблемы?
— Палочкобоги наслаждаются нативным луком-пореем.
— Парни, я не знаю, что вы тут обсуждаете, но настоящие гуру едят только «Мимозу».
— Господа, у вас же КРАБОВЫЕ ПАЛОЧКИ!
— Парни, так чё купить-то?

** Велосипеды
Ездил я себе, как все нормальные люди, на трёхколёсном велосипеде, стабильно протирая все три колёсика и меняя резину. Но вот недавно решил попробовать на вкус, так сказать, эти ваши хвалёные двухколёсники. После долгого выбора модели и пробования на рынке я отбросил все, кроме одной. Что вы, можете не кукарекать про "ололо ты не Ъ ололо ниасилил", я не дегенерат, чтобы ебаться с велосипедом дольше времени доставки + полчаса на настройку.

В общем после моего трёхколесничка впечатления сугубо отрицательные, особенно от переключения скоростей. И не только внешне блевать тянет от вида звёздочки, но и сама концепция хуёвая. Вид у велосипеда по дефолту омг — школьник распидарасил колёсищи АГРОМНЫИИИ ;)))). Руль тоже как говно выглядит, да и вообще — привет 90-е! Пластлиновый УГ внешний вид.
Не ну двухколёсник это пиздеееец, почему всё такое огромное и блядь будто школьником петей деланное? Дегенераты ебаные. Никакого вкуса и ума.
BMX выглядит гораздо лучше, но мой б-г, сколько там ненужного. Какие-то блядь пружины ОЛОЛО ПЫПРЫГУНЧЕГ ОЛОЛО КОЛЕСИКИ. Вы ебанулись там совсем? Велосипед для школьников-дегенератов что ли?
Колёса с шинами оказались неудобным говном, куда лучше мои цельнолитые.
С настраиваемостью все обстоит ещё хуже. Ковыряться в осях руками это знаете — 80ые. Нахуй такое.
В общем разочарован я, ничего хорошего двухколёсный велосипед предложить не может. Он реально хуже трёхколёсного с его прекрасным, отлаженным, хорошо выглядящим корпусом (не только эстетически но и с точки зрения рациональности).
Может быть, очень может быть какая-нибудь модель для начинающего предпринимателя (имеется в виду как альтернатива автомобилю) на первых порах, да и то только может быть.
И речи никакой не идет о не дай б-г доминировании, даже о лёгком превосходстве 2-х над 3-х.
Это не троллинг ни разу. Петухи с ниасилил идите нахуй, мне есть чем заняться помимо осиливания. Двухколёсным моделям нужно становиться ближе к юзеру или соснуть.
** Петухан Куриханыч Максималыч
Жила-была старуха, у нее сын Иван. Раз Иван уехал в город, а старуха одна осталась дома. Зашли к ней два одмина и просят срочно залогиниться на свой сервак, поскольку им сказали, что он упал. А старуха скупа была и говорит:
— Компа у меня нет, вон только телек ламповай.
А у самой под салфеточкой новый SandyBridge четырёхядернай, ну и на нём, как положено ПИТУХ ОС. Проведали это одмины говорят между собой:
— Погоди, старая! Мы тебя научим, как идти супротив сисадмина.
Вышли во двор, выпустили скотину, пришли и говорят:
— Бабушка! Скотина-то на улицу вышла!
Старуха заохала и выбежал скотину загонять. Одмины между тем достали из ранца походную флешку, ПИТУХА снесли нахуй, а вместо него заебошили инсталлятор GENTOO.
Старуха загнала скотину, пришла в избу и говорит:
— Загадаю я вам, одминчеги, загадку.
— Загадай, бабушка.
— Слушайте: в Спальнинске-Комнатинске, под Салфетинском, стоит ПЕТУХАН КУРИХАНЫЧ МАКСИМАЛЫЧ.
—  Эх, старая! Поздно хватилась: в Спальнинске-Комнатинске был Петухан Куриханыч Максималыч, да переведен в Девинск-Нуллинск, а теперь там КОМПИЛЯЙ СОБИРАИЧ. Отгадай-ка вот, бабушка, нашу загадку.
Но старуха не поняла одминской загадки.
Одмины посидели, поели черствой корочки с кислым квасом, пошутили со старухой, посмеялись над ее загадкой, простились и ушли.
Приехал из города сын и хочет зарубиться в КРУЗИС. Старуха сняла салфетку, запустила комп, и ждёт, смотрит как цифирки бегут. «Ай да ПИТУШОК, — думает про себя, — вишь как засорился — прочекаться не может». Загрузился, ан... Gentoo! Стоит, сука, и компиляться просит!
* Околочановское
** Йоба vs Кулфейс                                       :yoba:coolface:xvsy:

На мой взгляд йоба-фейс лучший.
Он как бы передает ту тонкую грань между тонкой иронией и гомерическим смехом.
В его тонком прищуре улавливается как самодовольство,так и нежный позыв к баттхерту.
Блядская рожа же всего лишь изображает эмоции успешного тролля,но в ней нет динамики, она статична.
Она показывает ситуацию уже после вброса, мол, вот я какой довольный, я потроллил.
Совершенно противоположная ситуация складывается с йоба-фейсом.
Он показывает сразу несколько действий одновременно - начало дискуссии(тролль смотрит и радуется тому сейчас свершится-на это указывают игриво сдвинутые зрачки глаз), момент вброса(здесь задействована ироничная и вызывающая улыбка), и уже саму ситуацию после провокации(здесь начинают играть и глаза и улыбка и вообще все в целом).
Я думаю что проблема блядской рожи в том, что она смотрит непосредственно на зрителя, и в том, что она слишком морщиниста(знак неповоротливости).
В итоге производится некое тяжелое, гнетущее впечатление.
Йоба-фейс, в свою очередь, производит впечатление легкости, коммуникабельности, готовности парировать любым аргументом.
Йоба легок на подьем, он всегда смотрит в будущее.

** Про троллефобию
Ебааать, было время, когда ты и понимаешь вроде, что с троллем или фантазером говоришь (кстати, школьники, вы считаете эти понятия взаимозаменяемыми, да?), но так все это интересно, что начинаешь подыгрывать.
А вы, уебаны, считаете каждый себя умнее всех. Почему ТЫ думаешь, что именно ТЫ такой охуенный задетектил тролля? Это не тролль. Это добрый дядька анон решил тебя развлечь, а ты на говно исходишь, гниденыш. Когда в круизис играешь тоже, наверное, бурчишь себе под нос "Чертовы тролли из Crytek!"?
Так вот, сосите хуй, быдлосы и учитесь у оп этого треда.
Спасибо, оп, потешил.
Я кончил и закурил.

** Бунт на радиве
[09.06.11 22:00-01:00] Бунт на радиве. Что лучше: брутфорс хостера или регистратора? Установка на сервер rtmpd, Apple Media Streaming, Microsoft Advanced Video Streaming, если сервер выдержит — прямо в эфире. Пидорение DJMPD, заебал сука. Набор ведущих для ANON.TV, хватит непонятной звукоеботы, только ВИДЕОХУЙНЯ. Видеорепорты как ебать еврейку и как выращивать грибы, растения, перепелов и многое другое. Снимаем порнуху силами диджейки. Приглашаются актеры, готовые сниматься в зоопроне, равно как и животные, которых будут ебать (обращение к бывшим диджеям). Возвращение Eorlas в новой роли. Это и многое другое на новом проекте: ANON.TV, увидимся в эфире!
* EOT
** Опыт
Я тебе вот такую вещь скажу, ты её обдумай хорошенько, очень хорошо, а потом реши для себя, лучше ли титанство или нет. Я для себя уже решил, что да, лучше, хотя раньше считал иначе. Итак.

Представь, что у тебя появится девушка. Ну да, хорошая, может, не идеальная и не очень красивая, но любящая. Ты ведь не рассчитываешь на супермодель, верно? И вот вы с ней будете жить. Да-да, будете делать все те смешные и глупые вещи из популярных паст, чесать друг друга за ушком и расчёсывать волосы, это всё замечательно. Не спеши рыдать от того, что у тебя этого не было/не будет, не всё так плохо. Читай дальше.

Пройдёт неделя. Месяц. Год. А она будет с тобой. Всегда рядом. И тебе вряд ли удастся побыть одному, даже если захочется. Придётся объяснять, зачем тебе это (а ты сможешь это вообще объяснить?), придётся говорить с ней, даже если у тебя будут более интересные дела или не будет настроения вообще говорить с кем-либо, захочется забиться в наушники или наоборот, включить громкую музыку (а если ей не понравится твоя музыка или её громкость? Придётся подавлять свои желания и подстраиваться). Придётся смотреть с ней кино или аниму, гулять (или правильнее сказать «выгуливать»?). Одним словом, себе ты принадлежать почти перестанешь. Иначе она обидится. Вы будете иногда ссориться, это неизбежно, идеальных людей нет, и интересы всегда сталкиваются. Извиняться. Мотать друг другу нервы. У тебя есть столько нервов? Есть столько времени? Ведь именно его начинает не хватать, как только появляется что-то интересное. Но тебе придётся по кусочкам ломать свою личность, свои пристрастия, интересы, подавлять желания и подменять их долгом. «Надо» в твоей жизни станет намного больше, ведь девушки без внимания увядают, и это внимание им нужно получать постоянно, а не только в первую неделю или до первого секса.

И хватит ли тебе духу от неё избавиться, если ты действительно начнёшь ценить _свою_ жизнь, _своё_ время и _свои_ интересы?

Окей. Ладно. Уговорил. Ты действительно на всё готов, лишь бы не быть одному. Просто сядь и честно продумай один месяц совместной жизни, что вы будете делать каждый день, каждый час. Включая выходные. Праздники. Утра, дни, вечера. Постарайся представить это в реальном времени, как это всё будет происходить. Теперь отмасштабируй на год. Потом на пять лет.

Ну как? Классная перспектива? Не забыл, что чем больше люди друг друга узнают, тем менее они друг другу становятся интересны? И после первой ночи вместе тяга к запретному плоду сократится вдвое, ведь ты уже вкусил. Остальное будет вторично.

Я знаю, что этим постом ничего не изменю в твоей жизни (скорее всего), потому что всё это надо ощутить и прочувствовать на себе. У меня не получилось радоваться жизни вместе. И вряд ли получится с кем-нибудь ещё, forever alone — это не просто слова, это не стиль жизни, это её суть. Суть моей жизни. И я, кстати, этому рад, ведь только так можно посвятить себя развитию, изучению нового, знакомствам с интересными людьми (пусть и виртуальным знакомствам), и я сам буду хозяин своей судьбе вместо повторения проторенной дорожки работа-семья-дети-старость-смерть, когда люди живут фактически лишь для создания потомства, а когда оно вырастает, тихо угасают с надоевшим(ей) супругом(ой), доживая годы на нищенскую пенсию в твёрдой уверенности, что они всё сделали правильно, как родители и деды завещали. Но маленький червячок сомнения грызёт их и шепчет, что ничего-то они в жизни не совершили, кроме порождения комка разумной биомассы, на что даже ума особого не надо.

Не паста, просто личный полезный, но далеко не самый приятный опыт

Ну вот и я о чём. А друзья и прочее — это намного проще. Мне от друзей, конечно, бывал прок, но рано или поздно наступает момент, когда все заебали и никто не нужен. Благо, друзья куда менее требовательны, чем девушки. А, и праздники тоже терпеть ненавижу, все эти подарки выдумывать, поздравлялки и прочую хуйню. И сам не праздную, предпочитаю устраивать праздники в дни, удобные лично мне, а не когда вся страна/планета дружно начинает нажираться по календарю.

ОП, ты ведь подсознательно и сам всё это знаешь и понимаешь, а отчаяние исключительно оттого, что ты не такой, как все, и что всем нравится жить по стандартам и правилам, а тебе нет. Из-за этого ты не можешь найти родственную душу и страдаешь, ведь тебе недоступна примитивная радость от распития жыгуля под семки в подъезде. Но разве ж это плохо? Научись находить радость в себе, в своих собственных поступках и самореализации, не ориентируйся на других. Пусть они живут как хотят. А ты иди своим путём и будь счастлив по-своему, иначе. Так, как удобно именно тебе.

И помни, всегда есть тот, кто всё равно тебе друг, и ты ему дорог. Хоть ты его не знаешь в лицо, а он тебя. Просто он не твоя личная армия, но ведь это совершенно неважно.
** Духи из таблички
Банга-тум, духи из таблички. Недавно читаю я эти символы(предыдущая табличка сломалась две зимы назад, видимо, прогневала духов) но уже проникся вашей мудростью.Посему, обращаюсь к вам за советом.Обязательный жертвенный кабан лежит в обычном месте, под скалой. Знали бы вы, каких трудов он мне стоил….

Дело в том, что появилась у нас одна самка(изображение подрисовано). Появилась она давно, и так же давно я за ней наблюдаю. Но проблема в том, что я… не знаю как называется, видимо ещё не придумали название, в общем я одиночка. Сижу целыми днями в пещере, пишу на стенах, читаю сию таблицу, сам слаб, а глава племени давно на меня подозрительно поглядывает. Зато начал считаться умным и иногда даже помогаю шаману. Тем не менее, в праве на выбор самки я последний, и последнее, что мне предлагали я с отвращением забил дубиной и съел этой зимойхватило, кстати, надолго.

Ещё в нашем племени есть альфа-самец. Он пытался даже свергнуть вождя, но проиграл, а за поражение добыл в одиночку мамонта. Мне кажется, он поглядывает на мою примеченную самку и хочет её на следующей делёжке.

Что мне делать, о духи таблички?
** А кто вы вообще такие, альфы?
А кто вы вообще такие, альфы?
Чем вы можете похвастаться кроме симпатичной внешности, красивого сильного тела и большого хуйца? Ничем! Ха-ха! Тяны любят вас только за вашу внешность, от которой они текут, и за так называемую брутальность, которая заключается лишь в излишней самоуверенности и завышенном ЧСВ - ведь вы же настоящие сОмцы. Да и то, такие тян - поголовно тупые шлюхи. К слову, овер 90% тян - тупые куски 
мяса с половой щелью вместо мозга. 
Ебаные альфы, вы не создаете ничего полезного, от вас нет никакой пользы, вы обуза даже для этого гнилого общества. Любой хикке, любой задрот, да даже любой обычный кун превосходят вас по уровню интеллекта и духовного развития. Хуже вас наверное только тупые мажоры-полуебки. Я не понимаю и откровенно недолюбливаю тянов, которые вместо нормальных кунов предпочитают вас. Внутренний мир, широкий кругозор, душевность, преданность - это уже не ценится. В моде няшные или наоборот брутальные морды, горы мускулов, наглость и выходящая за рамки разумного самоуверенность, ну и конечно-же хуи за 20 см. Бесспорно, в постели у альфы преимущество. Да, любая тян предпочтет ебаться скорее с мачо, чем с дрищом или жиробасом (Алсо, жиробасы - безвольные куски говна, они даже не люди, - смейтесь над их уебищностью, гоните их отовсюду, издевайтесь над ними). Но на этом ваши плюсы заканчиваются.
Как-же бесит, когда в большой компании с тянами обязательно находится накачанный красавчик, и не оставляет менее альфоватым кунам никаких шансов. Да отбивайте наших тянов сколько влезет, хоть усритесь! Я решил, что буду один. Всегда. Я не хочу чтоб моя будущая тян променяла меня на тупого накачанного орангутана с ватой вместо мозга, неебически охуенными кубиками на животе, огромным хуем и серой никчемной душонкой. А она променяет. Обязательно. Такова женская, блядь, природа - отдаваться более красивым, сильным и наглым. А я буду сидеть один, попивать виски и смотреть на то, как общество катится в собачью пизду, в какой-то мере благодаря вам. Буду сидеть и смеяться, когда 
вы бросите очередную ТП, или она бросит вас. Потому что вы никчемны. Бесспорно, у вас есть будущее. Ведь вы пользуетесь спросом у представительниц слабого пола. Вы обязательно найдете себе пизду на которой женитесь. Может быть ваша жена-шалава даже не будет бегать от вас налево. Вы наплодите таких-же бесполезных уебков. Новорожденные кричащие куски мяса от кобеля и шлюхи, как это мерзостно.. На этом все и кончится. В своей бесполезной старости вы поймете, что вы - куски дерьма. А сейчас я просто вам об этом ненавязчиво напомнил.
* Bitcoin
** Новый биткоин
Когда я получаю новый Биткоин, Сатоши подымает меня над полом и приближает к себе. Не так близко, чтоб поздороваться, но так высоко над вами, чтобы узнать вам,дешевкам, цену. Кто такой ты с гадким баксом в лапке, жалко и смешно трясущийся от жадности банка, чтобы отправить его своему говнодругу с говнорублём? Вы писькины плевки, получившие паспорта, вы спрессованный в толпу корм для рыбок, ваши лица сливаются в одну огромную жопу. Человек без Биткоина есть такая низкая тварь, что даже утопая в реке, я не подам ему руку. Когда я плачу своим Биткоином, в ответ я получаю тёплые носки, надёжный VPN, добрые вещества с silkroad. А не рев и скрежет чудовищ, которые обслуживают вас, тупых фиатных быдлов, на рынках и в магазинах. И неважно, голова у вас на плечах или череп, рога под кепкой или копыта в кедах — вы не люди. Вы орущая потная поверхность. Вы ворсинки ковра, по которому я хожу и роняю пепел. Когда я перевожу свой Биткоин на свой новенький компьютер, он прогибается всем корпусом и дрожит от восторга и счастья. Когда я вынимаю свою флешку с wallet.dat из кармана, карман рыдает. И когда я окончательно решу отделить ваше убожество от своего превосходства — я пойду и куплю второй Биткоин. А пока ну–ка скинулись мне на первый!
.
* Coding
** ПРЫЩАБА [концепт-документ]

Итак представляю вашему вниманию революционный вебтринольный стартап анонимной борды с поддержкой жаббера PRYSCHABA (expanded and remastered). Аналогичный концепт уже представлялся вашему вниманию несколько месяцев назад в /s/, но был написан в хуевой форме и посему не был воспринят с восторгом и трепетом. Так же с тех пор мне удалось немного попользоваться жуйкой (говно, не рикомендую) и вынести оттуда несколько удачных идей, а так же осознать уебищность некоторых вещей и внести поправки к ним, доведя тем самым прыдыдущий концепт до небывалой продуманности. 

Суть такова: имеется имагборда с традиционной веб-мордой (предположим, что оно работает и всех
устраивает). Так же имеется жаббер-сервер, который общается с движком борды. На жабер-сервере
имеется по юзеру на каждую доску, которые являются аналогом главной страницы доски, а так же на
каждый новый тред в борде на сервере создается новый уникальный пользователь с жидом по названию (номеру) треда (по умиранию треда юзер удаляется и его жид освобождается). Изначально юзер добавляет нужных доско-юзеров себе в ростер и этот юзер начинает слать ему ОП-посты всех созданных тредов в виде:
 
!аб. *одна_тян http://pryschaba.org/b/src/123.jpg
Привет прыщаба, я Кагами.
Есть одна тян.
 
!ав. http://pryschaba.org/b/src/124.jpg
Идите все нахуй.
 
!аг. Прыщебляди и в этом треде соснут хуйца.
 
Что за "!аб" и "!ав"? Это "номера" тредов. Почему это лучше цифр? Потому что их быстрее набрать, проще отличить, а так же они короче (на 2 буквы поместится 1024 треда). Нумерация не будет абсолютной, т.е. номера удаленных тредов (предположим, будет определенный лимит активных тредов на каждой борде, скажем в те же 1024 треда, которые обеспечиваются двумя буквами) будут потом использоваться (гетоебы идут нахуй или будут как быдло на тонированных девятках ловить себе номер "АА"). Что за *одна_тян? Это теги. Помогают искать на главной странице интересующие вас треды, а так же визуально отсеивать говно без чтения оп-поста. Почему "!", "%", "*" и (упомянутые ниже) "%", "=", а не другие символы, более интуитивно понятные? Потому что интуитивность это хорошо, а удобство набора намного лучше. Привыкать к такому синтаксису дело пары дней, а возможность набирать все без переключения раскладки и с одинаковым положением клавиш на рюской и латинской раскладке бесценна.
 
Допустим, юзеру понравился какой-то тред и он хочет его читать/отвечать. Он пишет боту "!кз" или "!кз хуй-пизда" (второе - если хочет вместе с подпиской отправить сообщение, опционально "!кз* сагаю топовый тред" для ответа без подписки на тред) и бот добавляет его жид в список рассылки тред-юзера, созданного на жабер-сервере. Этот юзер начинает отсылать всем подписанным на него все сообщения из треда, а так же через него можно писать в тред. Интерфейс общения с тред-ботом будет очень похож на борда-бота:
 
%а. http://pryschaba.org/b/src/123.jpg
Привет прыщаба, я Кагами.
Есть одна тян.
 
%б. ОП, **ХУИ СОСЕШЬ**?
 
%в. %б сосу обязательно
 
%г. вы тут охуели все?
 
%д. %а ты совсем, дружок, пизданулся с этими тян.
 
%е. %в тричую капчу.
 
Ну вы понели. Что за "%а"? Это номера постов. Начинаются с "а", заканчиваются допустим на "яя". Как писать сообщения? Просто отправьте их боту. Разметка: *курсив*, **полужирный**, `моноширинный` (похуй что апострофа нет в русской раскладке, все равно 98% моноширинного это код, который на варварской латинице), остальная разметка с латехом и аски-артом для пользователей платного аккаунта и пока не разглашается, нужно же зою и капусту стричь. Как прикладывать имаги? Отправлять их боту с комментарием, который будет постом, или отправлять сообщения начинающиеся с прямого линка на имаг на каком-нибудь имагообменном ресурсе (туда зальете прыщескриптами, ноубади карес).
 
Команды общения с ботом - \команда. Допустим, можно отписаться от треда (\нахуй), запросить конкретные сообщения (\аб \а;в;ев или диапазон \аб,$ (до последнего)), революционная команда \аб* выводящая рекурсивно все сообщения с последовательными ответами (допустим, максимальную "глубину" можно задать цифрой \аб*5) начиная от текущего, например для треда выше по команде "\е*" выведется:
 
%б. ОП, **ХУИ СОСЕШЬ**?
 
%в. %б сосу обязательно
 
%е. %в тричую капчу.
 
Для цитирования конкретного текста =хуй пизда=, для цитирования всего мессага (если сильно длинный, то будет обрезаться) =%аб, революционное =%д*совсем,пизданулся цитирующее из примера выше "совсем, дружок, пизданулся".
 
Няшки для интеграции веб-морды и жабера и остальное:
$РЕГИСТРАЦИЯ$, позволяющая серфить через веб-морду и добавлять подписки в жабер. Опционально постинг
без капчи для продавшихся в анальной рабство зою с передовыми отказоустойчивыми механизмами
присекания вайпа. Стандартный набор необходимых команд вроде \линк для получения линка на веб-морду треда; 10, 25, 50, 100 для получения списка тредов с данным и более количеством ответов и т.п..
 
Традиционной системы "бампов" нет, мессаги с анонсами от доска-юзера отправляются о каждом новом треде (для уменьшения нагрузки и удобства чтения можно сделать буфферизацию главной, и рассылать сообщения с определенным периодом вставляя туда сразу все "новое" за прошедшее время), но так же дополнительно отправляется анонс с существующим тредом по достижению в нем 10, 25, 50, 100 (и т.п.) ответов (цифры эмпирически корректируются).
 
FAQ.
Q: Уже хочу! Где скачать бесплатно без регистрации?
А: Нигде, развитие интернета еще не дошло до этой ступени эволюции.
 
Q: А оно вообще пишется?
A: Совсем пизданулись? Нет. По крайней мере мне об этом не известно.
 
Q: Я охуенный кодер на хаскеле и в два счета такое напишу, нужно?
А: Всем похуй, но можешь писать.
 
Q: Зачем это нужно?
А: Прыщаба не нужна, вы ошиблись.
 
Q: Если такое появится, то каких можно ожидать последствий?
А: Никаких последствий, даже на быдлохабре не напишут. Брат разве что может из 
комы не выйти.
 
Q: Будет же тормозить, епта! Че делать?
A: Кроме нескольких десятков прыщезадротов это нахуй никому не нужно, прыщабу можно будет хостить на нокии н900, я ручаюсь за достоверность предоставленной информации.
 
Можете спрашивать свои вопросы. Если что пропустил (уже немного поздновато, мог много чего забыть описать).
* Animu
** Про Мадоку
Дропнул на второй серии, 2/10, 2 за шрифты сабов, пиздатые были шрифты.
** Докторы, вы знаете, я очень одинок

Докторы, вы знаете, я очень одинок. Каждый день я прихожу домой, включаю на своей 50' плазме что-нибудь типо Rosario + Vampire, в правой руке сжимаю бокал виски со льдом, а в левой свой болт... и плачу, доктор! Плачу! Потому что японские школьники на экране гораздо счастливие меня! Я ненавижу себя за это! Я разбрызгиваю своё семя по всей комнате, уделываю плазму, ковёр, обои, чучело лично убитого ягуара и всё это размазывая сопли по всей комнате! а потом я беру бритву и делаю засечку на своей руке...
Нет, мысли о самоубийстве не посещали от аниме точно. Запрещать не следует, там всё правильно кажут. Насилие, секс, всё правильно. Пусть лучше детки реалии современного мира из мультиков увидят, чем из личного опыта на улице
* Internets
** Принудительный перевод на микроблоги в контакте
Начался 2010 год — всем похуй
4 января — самое высокое здание в мире построено — всем похуй
22 января — интернет в космосе — нихуя не изменилось
25 февраля — Проффесор — перзидент Украины — все по прежнему
29 марта — взрывы в метро — люди продолжают почесывать задницу
20 апреля — пизда нефтяной платформы — всем все еще похуй
лето — адовые пожары, пизда сатаны разверглась — уныние, еще одно пустое лето
6-7 августа — парад планет — год как год
28 сентября — Лужкова послали нахуй из ДС — жуйк умирает от уныния и упоротости, еще один ссаный год подходит к концу
Октябрь 2010 — перепись населения. — люди впадают в спячку
21 октября — ПРИНУДИТЕЛЬНЫЙ ПЕРЕВОД НА МИКРОБЛОГИ В КОНТАКТЕ! — ВЕСЬ МИР ТРЕПЕЩИТ! ГОД ПЕРЕМЕН! УЖАС, ВСЕ ТЕЧЕТ, ВСЕ МЕНЯЕТСЯ, МЫ НЕ УСПЕВАЕМ ЗА ВРЕМЕНЕМ!!! ТАКОГО ГОДА БОЛЬШЕ НИКОГДА НЕ БУДЕТ! УЖАС УЖАС УЖАС!!!!
* Безумные пословицы
** Bad ending
** Good ending

Шла Саша по шоссе и ХОРОШО ЕЙ БЫЛО ВЕДЬ ЭКЗАМЕНЫ СДАНЫ ПОСТУПИЛА В ПРЕСТИЖНЫЙ ВУЗ МОЛОДОЙ ЧЕЛОВЕК ПРЕДЛОЖЕНИЕ СДЕЛАЛ ВЕСНА ЛЮБОВЬ БУКЕТ РОЗ 

Идет медведь по лесу, видит — машина горит, сел НА ПЕНЕК ПОЗВОНИЛ ПОЖАРНЫМ ТЕ ПРИЕХАЛИ И ПОТУШИЛИ НИКТО НЕ ПОСТРАДАЛ ПОТОМ МЕДВЕДЮ ДАЛИ ГРАМОТУ СЧАСТЬЕ РАДОСТЬ КОВРОВАЯ ДОРОЖКА САЛЮТ ВЫХОДНОЙ ДЕНЬ ДЕТИ ИЗЛЕЧИВАЮТСЯ ОТ КОРИ А МЕДВЕДЯ В ЦИРК ВЗЯЛИ НА КОНФЕРАНС И ВСЕ СЧАСТЛИВЫ. 

Любопытной Варваре на за базаре ПРОВЕЛИ ЭКСКУРСИЮ ПЛЮШЕК С ПЫЛУ С ЖАРУ НАСОВАЛИ В ПОДОЛ КУЗНЕЦ МОЛОДОЙ ПОДКОВА НА СЧАСТЬЕ СОЛНЦЕ СВЕТИТ ГОМОН ЗАМЕЧАТЕЛЬНЫХ ЛЮДЕЙ ЛАСКАЕТ СЛУХ 

Слезами делу КАКАЯ НИКАКАЯ А ПОДМОГА ГЛЯДИШЬ КТО ВОЙДЁТ В ПОЛОЖЕНИЕ ПРИЛЕТИТ В ВЕРТОЛЁТЕ БЕСПЛАТНО ПОКАЖЕТ КИНО ЭСКИМО ПОДАРИТ ДАЧУ СИДИШЬ ПОД СОСНАМИ ЖИЗНЬ УДАЛАСЬ НЕ ЗРЯ ПОПЛАКАЛ 

Тридцать три корабля лавировали, лавировали, да и КРАСАВЦЫ–ТО КАКИЕ ВЫ ТОЛЬКО ПОСМОТРИТЕ МАНЕВРИРУЮТ КАК БОГИ ЛИЧНЫЙ СОСТАВ С ИГОЛОЧКИ КАПИТАНЫ УЛЫБАЮТСЯ ФУРАЖКИ БЛЕСТЯТ САЛЮТ ФЕЙЕРВЕРК ТОРЖЕСТВО–ТО КАКОЕ 

В тихом омуте черти ИГРАЮТ В ШАХМАТЫ ОБСУЖДАЮТ КАНТА ВСЁ ПРИБРАНО НИКАКОГО АЛКОГОЛЯ ТИХО ИГРАЕТ КРИСТИНА АГИЛЕРА БУДТО В РАЙ ПОПАЛ 

Семеро одного ЖДУТ, БЕСПОКОЯТСЯ, ПЕРЕЖИВАЮТ, А ПО ЕГО ПРИШЕСТВИИ ПОДБАДРИВАЮТ, УСПОКАИВАЮТ 

Бог дал, бог и НАВАЛИЛ СВЕРХУ ЕЩЁ ДОБРА С ПОДЛИВОЙ НА МУЖИК НИ В ЧЁМ НЕ НУЖДАЙСЯ ПУСТЬ ДЕТИ ТВОИ УЧАТСЯ В КЕМБРИДЖЕ А У ЖЕНЫ СИСЬКИ ОТРАСТУТ ТОЛЬКО НЕ ПЕРЕЖИВАЙ

Я буду долго гнать ВЕЛОСИПЕД В ГЛУХИХ ЛУГАХ ЕГО ОСТАНОВЛЮ НАРВУ ЦВЕТОВ И ПОДАРЮ БУКЕТ ТОЙ ДЕВУШКЕ КОТОРУЮ ЛЮБЛЮ ДИКО ВРАЩАЯ ГЛАЗАМИ 

По танку вдарила болванка ДА И ПОХУЮ БРОНЯ ВЫДЕРЖАЛА ПРОРЫВАЕМ ЛИНИЮ ОБОРОНЫ ЗАДАНИЕ ВЫПОЛНЕНО ДАЛИ ГЕРОЯ И ОТПУСК НА НЕДЕЛЮ ОБНЯЛ МАТЬ И ОТЦА МОЛОДАЯ НАКОНЕЦ–ТО УЗНАЛА КАКОЙ У ПАРНЯ БЫЛ КОНЕЦ

Сунул Грека руку в реку, рак ЕМУ АККУРАТНО КЛЕШНЮ ПОДАЛ ПОЗДОРОВАЛСЯ ВЕЖЛИВО ПРО ЗДОРОВЬЕ СПРОСИЛ ПРО ДЕТИШЕК ЗАХОДИТЕ КАК-НИБУДЬ НА ЧАЙ УВАЖАЕМЫЙ ГОВОРИТ.

Без труда не выловишь и рыбку из МОООООООООООООРЬКООООООООООООО ДУЕТ БРИЗ МЫ ПЬЕМ КОКТЕЙЛИ И ТАНЦУЕМ ЛАЛАЛА

У семи нянек ребёнок НАКОРМЛЕН СУП НАВАРЕН КВАРТИРА НАЧИЩЕНА ИПОТЕКА ВЫПЛАЧЕНА ВЗАИМОПОНИМАНИЕ УЮТ В МОЛОДОЙ СЕМЬЕ

Сапожник без сапог КЕДЫ НОСИТ ЭКСТРЕМАЛ КОНТРАКТ ПОДПИСАН ЖЕНЕ ШУБУ КУПИЛ ДАЧУ ПОСТРОИЛ МОЛОДЕЦ И ОПОРА СОЦИУМА

Разбежавшись прыгну со скалы ТРОЙНОЕ САЛЬТО ВСЕ АППЛОДИРУЮТ ЧЕМПИОН МЕДАЛИ ГОРДОСТЬ СТРАНЫ

Семь раз отмерь А ПОТОМ ВСЁ ЗАБИРАЙ ЧЕГО МЕРИТЬ-ТО ДОБРА ЭТОГО НАВАЛОМ НЕ ЖАЛКО ДЛЯ ТАКОГО ЧЕЛОВЕКА НИЧЕГО ЕЩЁ ЗАХОДИ ВСЕГА РАДЫ

На воре шапка ЧЕСТНО ЗАРАБОТАННАЯ ДА ОН И НЕ ВОР ВОВСЕ ПОРЯДОЧНЫЙ ГРАЖДАНИН А КТО ЕГО ВОРОМ НАЗВАЛ ОШИБСЯ ВСЕГО ЛИШЬ 

Я твой дом труба ОТРЕМОНТИРОВАЛ ВАХ КРЫШУ ЕЩЕ ПОЧИНИЛ И ВСЕ БЕСПЛАТНО ДОРОГОЙ ПУСТЬ У ТЕБЯ ВСЕ ХОРОШО БУДЕТ ЦВЕТЫ АПЕЛЬСИНЫ ВОТ ВОЗЬМИ ЕЩЕ НЕ ЗА ЧТО ДОРОГОЙ БУДЬ СЧАСТЛИВ

Жена Аршавина спршивает: -Дорогой, где ты был? -ВЫИГРЫВАЛ У СБОРНОЙ БРАЗИЛИИ 9:0 В ФИНАЛЕ ЧМ МЕДАЛЬ ДАЛИ ПОГОДА СУПЕР СОЛНЦЕ ПОЕХАЛИ НА МОРЕ

Это интернет, тут могут ДАТЬ ПОЛЕЗНЫЙ СОВЕТ ПОМОЧЬ С КУРСАЧОМ УВЕЛИЧИТЬ ЧЛЕН СКАЧАТЬ БЕСПЛАТНО БЕЗ РЕГИСТРАЦИИ И СМС

И без капса это была бы унылая хуета. А так КАПС РАБОТАЕ ЛАМПОЧКА ГОРИТ БУКВЫ ЧЁТЧЕ ГЛАЗА НЕ НАПРЯГАЮТСЯ ЗРЕНИЕ ПО ЕДИНИЦЕ
** Sad ending
Шла Саша по шоссе ПРИШЛА ДОМОЙ РАЗОГРЕЛА ВЧЕРАШНИХ КОТЛЕТ С МАКАРОНАМИ ПОХОДИЛА НЕМНОГО ПО КОМНАТЕ СЕЛА У ОКНА И ПРОСИДЕЛА ТАК ДО ВЕЧЕРА ПОТОМ ЛЕГЛА СПАТЬ УСНУЛА БЫСТРО ПОТОМУ ЧТО НЕ О ЧЕМ БЫЛО ДУМАТЬ ЗАВТРА ОПЯТЬ ВЕСЬ ДЕНЬ СВОБОДНЫЙ 


Ехал Грека через реку, ВДРУГ ВОЗНЕНАВИДЕЛ СЕБЯ ВСЁ ВОКРУГ ВЕСЬ МИР ХОТЕЛ БЫЛО ВЫКОЛОТЬ СЕБЕ ГЛАЗА ЧТОБЫ НЕ ВИДЕТЬ БОЛЬШЕ НЕСОВЕРШЕНСТВА ЭТОГО МИРА ПРЫГНУТЬ В РЕКУ И ИСТЕРИЧЕСКИ СМЕЯТЬСЯ ПОКА РАКИ БУДУТ ЖРАТЬ ЕГО ПЛОТЬ ЗАЖИВО НО ПОБОЯЛСЯ ПОТОМ КАК-ТО РАЗ ПОШЁЛ В ЦЕРКОВЬ ВСТРЕТИЛ ТАМ ПРИЯТНУЮ ЕВРЕЙКУ ЗАЖИЛ С НЕЙ ВМЕСТЕ ПОТОМ ЖЕНИЛСЯ И ПОДАРИЛ ЖИЗНЬ СВОИМ ДЕТЯМ 


тридцать три корабля лавировали лавировали МОРЯКИ НА БОРТУ МЕЧТАЛИ О ДРУГИХ СТРАНАХ И ОБРАЗЕ НАСТОЯЩЕЙ МУЖСКОЙ ПРОФЕССИИ В ДЕТСТВЕ А ПОЛУЧИЛИ ГРЯЗНЫЕ ТЕЛЬНЯХИ И КИЛОТОННЫ БЫТОВЫХ ТОВАРОВ КОТОРЫЕ ОНИ ПОСТАВЛЯЮТ ОБЩЕСТВУ ПОТРЕБЛЕНИЯ В РАЗНЫХ СТРАНАХ 


на дворе трава на траве дрова ГДЕ ЖЕ ВОСПЕТОЕ СТОЛЬКИМИ НЕГЛУПЫМИ ЛЮДЬМИ ПРОСВЯЩЕНИЕ ОТ ПРОСТОЙ ЖИЗНИ НА ЛОНЕ ПРИРОДЫ ДУМАЛ УЙТИ ОТ АБСУРДА ЦИВИЛИЗАЦИИ А ПОЛУЧИЛ АБСУРД ЕСТЕСТВЕННЫЙ БОГОМ ДАННЫЙ ВО ВСЕЙ СВОЕЙ ЯСНОСТИ НО ДОДУМАТЬ НЕ УСПЕВАЕШЬ ПОТОМУ ЧТО СКОРО ОСЕНЬ А ПОТОМ И ЗИМА НУЖНО ЗАПАСАТЬСЯ ДРОВАМИ ЧТОБЫ БЫЛО ЧЕМ ТОПИТЬ А РАЗ В НЕДЕЛЮ ЧИСТИТЬ ПЕЧКУ ОТ ЗОЛЫ РУКИ ВСЕ В САЖЕ ПОТОМ ОТМЫВАТЬ ЕЩЁ ПОЛ-ДНЯ ВОДА В КОЛОДЦЕ СТУДЕНАЯ ПОЧЕМУ Я РОДИЛСЯ В СРАНОЙ РАШКЕ TECUM HABITA ET NORIS QUAM SIT TIBI CURTA SUPELLEX 


Я тебя любил, цветы тебе дарил, ВРОДЕ КРАСИВЫЕ НУ ПО КРАЙНЕЙ МЕРЕ ДОРОГИЕ Я ВСЮ НЕДЕЛЮ РАБОТАЛ НА ЗАВОДЕ И СМОГ КУПИТЬ ТОЛЬКО ЭТОТ БУКЕТ НЕТ Я НЕ ХОЧУ ДЛЯ ТЕБЯ ТАКОГО БУДУЩЕГО ТЫ СЛИШКОМ ХОРОША ДЛЯ МЕНЯ А МНЕ ДОСТАТОЧНО И ЛЕНЫ ИЗ ЦЕХА ПОКРАСКИ У НЕЁ ПРЫЩИ ЗА УШАМИ Я ВИДЕЛ ПОКА СТОЯЛ ЗА НЕЙ В ОЧЕРЕДИ В СТОЛОВОЙ НО С НЕЙ Я НЕ ЧУВСТВУЮ СЕБЯ ТАКИМ НИЧТОЖЕСТВОМ ВОТ ТЕБЕ БУКЕТ И НЕ ЗВОНИ МНЕ БОЛЬШЕ ПОЖАЛУЙСТА 


Трус не играет в хоккей, В ЭТОМ ЖЕ НЕТ НИКАКОГО СМЫСЛА КАКАЯ РАЗНИЦА КТО ПОБЕДИТ КАК ВООБЩЕ МОЖНО ИСПЫТЫВАТЬ УВЛЕЧЕНИЕ ОТ ЭТОЙ ИГРЫ ИЛИ КАКОЙ-ЛИБО ДРУГОЙ ТЕМ БОЛЕЕ ЕСЛИ СМОТРЕТЬ ЕЁ ПО ТЕЛЕВИЗОРУ 


еду я по выбоине из выбоины ТРИ МЕСЯЦА В ГИПСЕ ПЬЮ СОК ЧЕРЕЗ ТРУБОЧКУ ФАТАЛЬНАЯ ДЕТЕРМИНИРОВАННОСТЬ НАШЕГО МИРА ДАВИТ НА МЕНЯ ПОЧЕМУ Я НЕ ПРОЕХАЛ ДВУМЯ САНТИМЕТРАМИ ЛЕВЕЕ Я БЫ ВСЁ ОТДАЛ ЧТОБЫ ВООБЩЕ НЕ ВЫХОДИТЬ ИЗ ДОМА В ТОТ ДЕНЬ Я БОЛЬШЕ НИКОГДА НЕ ВЫЙДУ ИЗ СВОЕЙ КВАРТИРЫ ХОТЯ ЭТО И НЕ ГАРАНТИРУЕТ МОЮ БЕЗОПАСНОСТЬ НО ПО КРАЙНЕЙ МЕРЕ ЗНАЧИТЕЛЬНО СОКРАЩАЕТ РИСК 


Карл у Клары украл коралы а Клара ЗАСУДИЛА КАРЛА ТОТ СЕЛ В ТЮРЬМУ ВПРОЧЕМ ОН ДАВНО ПОТЕРЯЛ ВСЯКИЙ ИНТЕРЕС К ЖИЗНИ И НЕ ВИДИТ СМЫСЛА В ТОМ ЧТОБЫ СЧИТАТЬ ДНИ ДО ВЫХОДА НА ВОЛЮ СИДИТ В СВОЕЙ КАМЕРЕ ЧИТАЕТ КНИГИ СМОТРИТ В ОКНО СРАВНИВАЕТ СЕБЯ С ТОМОМ УЭЙТСОМ ИЗ ОДНОГО ФИЛЬМА ДЖАРМУША 


Какой ты молодец, если ОКОНЧИЛ ШКОЛУ С ДВУМЯ ТРОЙКАМИ ПОСТУПИЛ В ПРИЛИЧНЫЙ ВУЗ ОКОНЧИЛ ЕГО УСТРОИЛСЯ НА РАБОТУ С ДОСТОЙНЫМ ЗАРАБОТКОМ ГОЛОСОВАЛ НА ВЫБОРАХ ПОКУПАЛ ОДЕЖУ ЕДУ МЫЛО В МАГАЗИНАХ ИНОГДА ДАЖЕ ПОДДЕРЖИВАЛ ОТЕЧЕСТВЕННОГО ПРОИЗВОДИТЕЛЯ МАШИНУ ВПРОЧЕМ КУПИЛ ИНОМАРКУ ЧУТЬ ПОДНАКОПИВ ЗАВЁЛ СЕМЬЮ ВОСПИТАЛ ДЕТЕЙ ИНОГДА ВРАЛ ИНОГДА БЫЛ ЧЕСТНЫМ ИНОГДА ЖИЛ ИНОГДА НЕТ 


на горе арарат рвала варвара виноград И ДУМАЛА ЧТО В ДЕТСТВЕ КАЖЕТСЯ ОН БЫЛ КУДА ВКУСНЕЕ А СЕЙЧАС И ВИНОГРАД НЕ ТОТ И САМА ОНА УЖЕ ДАВНО НЕ ТА НАИВНАЯ МАЛЕНЬКАЯ ДЕВОЧКА КОТОРАЯ ХВАСТАЕТСЯ КАК ЗДОРОВО ОНА УМЕЕТ ПИСАТЬ СВОЁ ИМЯ КТО СЕЙЧАС УДИВИТСЯ ЕСЛИ ТЫ УМЕЕШЬ КРАСИВО НАПИСАТЬ СВОЁ ИМЯ А МЕЖДУ ТЕМ ЭТО ЕДИНСТВЕННОЕ ЧЕМ ДЕЙСТВИТЕЛЬНО ХОТЬ СКОЛЬКО-НИБУДЬ ИМЕЕТ СМЫСЛ ХВАСТАТЬСЯ 


Во поле затопали кони А В ГОРОДЕ УСТАЛЫЕ КЛЕРКИ ВИДЯТ ИХ В ПОЛУДРЁМЕ СТОЯ В ПРОБКАХ ПО ПУТИ В СВОИ ЗАТХЛЫЕ НОРКИ 


шит колпак не по-колпаковски НО Я УЖЕ УСТАЛ ХОДИТЬ ПО МАГАЗИНАМ ВОЗЬМУ ЭТОТ ОДЕВАЮ СМОТРЮСЬ В ЗЕРКАЛО ГОСПОДИ КАКИМ ИДИОТОМ Я В НЁМ ВЫГЛЯЖУ НО В ЭТОМ СЕЗОНЕ НА НИХ МОДА ВЫКЛАДЫВАЮ СУТОЧНЫЙ ГОНОРАР НА КАССЕ И ИДУ ДОМОЙ 


говорил попугай попугаю: "я тебя, попугай, попугаю". Отвечает ему попугай РОМКА ДУРАК А ПРО СЕБЯ ДУМАЕТ СРАНЬ ГОСПОДНЯ Я ЖЕ ПОПУГАЙ ВОТ ОНА ЭКЗИСТЕНЦИАЛЬНАЯ ИРОНИЯ Я МОГУ ТОЛЬКО ПОВТОРИТЬ УЖЕ УСЛЫШАННУЮ ПРЕЖДЕ ФРАЗУ ПОЖАЛУЙСТА ПУСТЬ СЮДА ПРИДЁТ ЧЕЛОВЕК И ПРОИЗНЕСЁТ ВСЕ МОИ МЫСЛИ ТОГДА Я СМОГУ ИХ ПОВТОРИТЬ 


Шел Егор через двор Нес топор чинить забор ВСПОМНИЛ ЧТО-ТО СМУТНОЕ ИЗ ШКОЛЬНОЙ ПРОГРАММЫ ЛИТЕРАТУРЫ ЗАГЛЯНУЛ К СВОЕЙ УЧИТЕЛЬНИЦЕ СПРОСИЛ НА НЕДЕЛЮ ЗАБРОСИЛ ВСЕ ДЕЛА ЧИТАЛ ПОТОМ ЗАРУБИЛ БАБУШКУ СОСЕДСКУЮ СЕЛ В ТЮРЬМУ А ЗАБОР ТАК И СТОИТ СЛОМАННЫЙ 


Галка села на забор Грач завел с ней разговор ДАВАЙ ПОЛЕТИМ НА ЮГ ДАЛЕКО-ДАЛЕКО ТУДА ГДЕ МОРЕ Я СЛЫШАЛ ТАМ ЕСТЬ ТАКИЕ БОЛЬШИЕ БЕЛЫЕ ПТИЦЫ ОНИ ЛОВЯТ РЫБУ ПРЯМО НА ЛЕТУ ПОДНЫРИВАЯ ПОД СВЕЖИЕ СОЛЁНЫЕ ВОЛНЫ МОЖЕТ И МЫ СМОЖЕМ СТАТЬ ТАКИМИ ЖЕ БЕЛЫМИ И ЧИСТЫМИ НУ ИЛИ ХОТЯ БЫ НАШИ ДЕТИ А ГАЛКА ЕМУ ГАЛ-ГАЛ 


Кукушка кукушонку купила КУЛЁК ЧЕРВЯЧКОВ ДАЙ ДУМАЕТ ПОРАДУЮ СЫНОЧКА А ПОТОМ ВДРУГ ВСПОМНИЛА ЧТО ОСТАВИЛА ЕГО В ЛАСТОЧКИНОМ ГНЕЗДЕ КОГДА ТОТ ЕЩЁ БЫЛ ЯЙЦОМ СЕЛА НА ПРОВОД И ЗАПЛАКАЛА 


расскажи мне про покупку про какую про покупку НУ А ПРО ЧТО ЖЕ ЕЩЁ НАМ ГОВОРИТЬ ШЕСТЬ ЛЕТ НЕ ВИДЕЛИСЬ СО ШКОЛЫ ТУТ ВДРУГ ВСТРЕТИЛИСЬ В ТОРГОВОМ ЦЕНТРЕ Я ВООБЩЕ НЕ ВЕРЮ ЧТО МЫ КОГДА-ТО БЫЛИ ЗНАКОМЫ МНЕ КАЖЕТСЯ ЗДЕСЬ КАКОЙ-ТО ПОДВОХ НЕ МОЖЕТ БЫТЬ ЧТОБЫ ВСЁ БЫЛО ТАК ПРОСТО КАК Я СТАЛ ТЕМ КТО Я ЕСТЬ ГДЕ Я НЕТ МНЕ НЕ НУЖНА СКИДКА НА ВАШУ СРАНУЮ ОБУВЬ ЛУЧШЕ СКАЖИТЕ МНЕ ЧТО Я ЗДЕСЬ ДЕЛАЮ 


Шел мужик по улице ПРОВАЛИЛСЯ В КАНАЛИЗАЦИЮ СМОТРИТ ТАМ ДРУГОЙ МИР НИЧЕГО ОБЩЕГО С НАШИМ НЕ ИМЕЮЩИЙ ПРЕКРАСНЫЙ ЧИСТЫЙ ИДЕАЛЬНЫЙ НЕТ В НЁМ НИЧЕГО ТЕЛЕСНОГО НЕТ ГРЕХА НЕТ СМЕРТИ НО МУЖИК СВОЕЙ ИНДИВИДУАЛЬНОСТИ В НЁМ НЕ ТЕРЯЕТ КАК У АНТИЧНЫХ ФИЛОСОФОВ НЕТ ОН ВОЛЕН НАБЛЮДАТЬ ЭТОТ МИР И УЧАСТВОВАТЬ В ЕГО ЖИЗНИ ПО МЕРЕ СВОИХ СОБСТВЕННЫХ СИЛ И ВОЗМОЖНОСТЕЙ КОТОРЫЕ НАДО СКАЗАТЬ ВЫРОСЛИ СООБРАЗНО С ЭТОЙ РЕАЛЬНОСТЬЮ ХОДИТ МУЖИК И ДУМАЕТ А ВЕДЬ МЫ ЖЕ СЮДА СРЁМ НУЖНО ПОЙТИ РАССКАЗАТЬ ВСЕМ ЧТОБ ПРЕКРАТИЛИ ЧТО ЕСТЬ ДРУГОЙ МИР ВЕРНУЛСЯ А ЗДЕСЬ ПИЗДЕЦ ВОЙНА ГОЛОД ЛЮДИ ДРУГ ДРУГА УБИВАЮТ ТРАХАЮТСЯ ЖРУТ МЁРТВЫХ ЖИВОТНЫХ НЕБО СЕРОЕ ПОНЯЛ МУЖИК ЧТО НЕ ИЗМЕНИТЬ НИЧЕГО ХОТЕЛ СЛЕЗТЬ ОБРАТНО А ЛЮК УЖЕ ЗАКРЫЛИ ПОЖАЛ ПЛЕЧАМИ И ПОШЁЛ ДАЛЬШЕ 


два кольца два конца а посередине ДУРНАЯ БЕСКОНЕЧНОСТЬ ЧЕРЕДА РОЖДЕНИЙ И СМЕРТЕЙ ОДНА БЕССМЫСЛЕННЕЕ ДРУГОЙ НИЧЕГО УЖЕ НЕ СДЕЛАТЬ ЖРИ АНТИДЕПРЕССАНТЫ И СЧИТАЙ СУММУ В СТОЛБИК 


встречают по одёжке, а провожают КАК МОЖНО СКОРЕЕ ПРОВАЛИВАЙТЕ И НИКОГДА БОЛЬШЕ НЕ ПРИХОДИТЕ КО МНЕ ВЫ НЕ ВЫТИРАЕТЕ НОГИ ПРИ ВХОДЕ А Я ВООБЩЕ-ТО МОЮ ЗДЕСЬ ПОЛ ВЫ БЕРЁТЕ МОИ КНИГИ БЕЗ СПРОСУ И ПОТОМ КЛАДЁТЕ ИХ В ДРУГОЕ МЕСТО ТАК ЧТО Я НЕ МОГУ ИХ НАЙТИ ПОТОМ ОБЪЯТЫЙ УЖАСОМ И С ТРЯСУЩИМИСЯ РУКАМИ ПО ПОЛ-ЧАСА ЧТО ВЫ ЗДЕСЬ ЗАБЫЛИ ОСТАВЬТЕ МЕНЯ УЖЕ НАКОНЕЦ В ПОКОЕ НЕТ КО МНЕ НЕЛЬЗЯ СЕГОДНЯ ПИТЬ ПИВО КТО ПРИДЁТ КО МНЕ В ГОСТИ ОКАЖЕТ МНЕ ЧЕСТЬ КТО НЕ ПРИДЁТ ДОСТАВИТ УДОВОЛЬСТВИЕ 


кто рано встает, тому бог ГОРЬКИЙ КОФЕ ЗАКОНЧИВШАЯСЯ ЗУБНАЯ ПАСТА ЗАСКОЧИЛ В МАРШРУТКУ НО ВСТАЛ В ПРОБКУ ВСЁ РАВНО ОПОЗДАЁШЬ КУДА ТАМ ТЕБЕ НАДО ЗАБЕЙ ХОТЬ БЫ ПОКУРИТЬ УСПЕТЬ СПОКОЙНО И ТО ХОРОШО НОЧНЫЕ ГРУЗЧИКИ СПАСАЮТ ЗЯБКОЕ УТРО РАННЕЕ ЭТО ВЕСНА ИЛИ ОСЕНЬ ОТКУДА НА СУХИХ ДЕРЕВЬЯХ ПОЧКИ ПТИЦЫ КРУЖАТ НЕ ЗНАЯ УЛЕТАТЬ ИМ ИЛИ ВОЗВРАЩАТЬСЯ 


Шапкой Саша шишки сшиб ОНИ ПОПАДАЛИ РАНЬШЕ ВРЕМЕНИ ЕЩЁ НЕСОЗРЕВШИЕ НЕ БУДЕТ В ЭТОМ ГОДУ НОВЫХ ПОБЕГОВ У МОГУЧЕЙ ЕЛИ КОТОРОЙ УЖЕ ТРИ С ЛИШНИМ СОТНИ ЛЕТ ОНА НИЧЕМ НЕ ЛУЧШЕ ЧЕЛОВЕКА НО ХОТЯ БЫ НИКОГДА НЕ ВРАЛА И НЕ СИДЕЛА ВКОНТАКТЕ НАДЛОМИТСЯ ОТПУСТИТ ПТИЦ СО СВОИХ РАЗЛАПИСТЫХ ВЕТВЕЙ РУХНЕТ ОБЕССИЛЕВ НА ПРОВОДА И ЗАТИХНЕТ ВСЁ ВОКРУГ 


не скоро сказка сказывается, а скоро ПРОХОДИТ ЖИЗНЬ ТАК НИЧЕГО НЕ УСПЕЛ ТОЛКОМ ХОТЯ ПРОСТО ПЫТАЛСЯ БЫТЬ ЧЕСТНЫМ С САМИМ СОБОЙ НЕ ДЕЛАТЬ ТОГО ЧТО СЧИТАЛ НЕПРАВИЛЬНЫМ 


Мало мыло мылилось А вода вся вылилась ТЕПЕРЬ ХОДИТЬ ВЕСЬ ДЕНЬ ПОТНОМУ ЕЩЁ СИЛЬНЕЕ ЧЕМ ОБЫЧНО ОЩУЩАЯ СВОЮ НЕСОВЕРШЕННОСТЬ ЗАЧЕМ ВСЁ УСТРОЕНО ТАК КАК МОЖНО ВООБЩЕ БЫЛО ПРИДУМАТЬ ТАКОЙ БРЕД ГОНИТЕ И ДАЛЬШЕ ПРО СВОБОДУ В НЕОБХОДИМОСТИ НЕУЖЕЛИ ВЫ ПРАВДА ДУМАЕТЕ ЧТО МИР НЕЛЬЗЯ БЫЛО УСТРОИТЬ ЛУЧШЕ 


В Луку Клим луком кинул А ЛУК ВЗЯЛ ДА И УЛЕТЕЛ В НЕБО ФИЗИКИ ОБОСРАЛИСЬ КАК ТАК МОЖЕТ БЫТЬ ВЕДЬ ЕСТЬ НЬЮТОН И ГРАВИТАЦИЯ ПОЧЕСАЛИ РЕПЫ СПОРИЛИ ДОЛГО НАПИСАЛИ ЕЩЁ ПАРУ УЧЕБНИКОВ И УСПОКОИЛИСЬ 


Ела Нина свинину КАКАЯ РАЗНИЦА ЧТО ЕСТЬ ВСЁ РАВНО ВСЕМ ПИЗДА
** Volume 2
Дым сигарет с ментолом пьяный угар качает. И УПАЛА ПЬЯНАЯ ПИЗДА ТУПИЦА ЕБАЛОМ ОБ АСФАЛЬТ ЗАБЛЕВАЛА ПОРВАНЫЕ СИСЬКИ РАСХУЯРИЛО В ПИЗДУ ТВАРЬ ЕБЛИВАЯ НАЖРАЛАСЬ И ВЫЕБАЛИ СПИДОЗНЫЕ ХАЧИ В БЫДЛЯЦКОМ КЛУБЕ. 

Товарищ сержант, два часа до рассвета НЕ НАДО МЕНЯ ПО ПОЧКАМ ДУБИНКОЙ АААААА БЛЯТЬ ГАЗ СЛЕЗОТОЧИВЫЙ УУУУУУУ ВОЛКИ ПОЗОРНЫЕ НЕ БЕЙТЕ Я СТУДЕНТ. 
ни клубных тусовок, ни бега с утра, ни поцелуя белого яда, ни поз кама-сутры, ни града петра, а града этого, ничего не надо И ОТЪЕБИТЕСЬ ОТ МЕНЯ УЖЕ, СРАНЫЕ УЁБКИ, Я ПРОСТО В МЕТРО ИДУ БЛЯТЬ, ЧТО ТЫ МНЕ ПИХАЕШЬ СВОИ СРАНЫЕ ЛИСТОВКИ, НОС СЕЙЧАС 
СЛОМАЮ К ПИЗДЕ СОБАЧЬЕЙ. 
о-о-оу, зеленоглазое такси, о-о-оу притормози притормози 750 РУБЛЕЙ ДО ЦЕНТРА ДА ТЫ ВООБЩЕ ОХУЕЛ ПИДОРАС 

Чучело-мяучело на трубе сидело. Чучело-мяучело песенку запело ХУЛИ ТЫ ПОЁШЬ В 5 УТРА НЕВЕДОМАЯ ХУЙНЯ. Я НА ЗАВОДЕ ДВЕ СМЕНЫ ОТПАХАЛ СУКА РАСПЕЛСЯ ТУТ, ЩАС ПОДНИМУСЬ И НАХУЙ С ЭТОЙ БЛЯДСКОЙ КРЫШИ ТЕБЯ ПОД ЖОПУ СПИХНУ. 

я был весел и беспечен, просто жил, как сам хотел. синяками был отмечен и согрет был теплом женских тел А ПОТОМ МЕНЯ НА УЛИЦЕ ОСТАНОВИЛИ НУ-КА ДОКУМЕНТЫ ПРЕДЪЯВИ, АГА, ВАСИЛИЙ ПЕТРОВИЧ, ЗАБИРАЕМ ЕГО? С НАМИ В ВОЕНКОМАТ ПОЕХАЛИ, ВОЛОСАТИК, СЛУЖИТЬ БУДЕШЬ, АХ ТЫ Ж ЁБАНЫЙ ТЫ НАХУЙ! 

Так и надо — все говорят, так и надо — сам виноват, НУ А ХУЛИ ТУТ ЕЩЕ СКАЖЕШЬ? КОСАРЬ СУНУЛ БЫ В ЗАЧЕТКУ В АРМИЮ НЕ ПОШЕЛ БЫ МУДАЧИНА ТЫ ПРОСТОФИЛЯ

Антошка, Антошка, пойдем копать картошку СУКА ТУПАЯ МРАЗЬ ДРУЗЬЯ С ГОЛОДУ ПУХНУТ МАТЬ КОТА СОЖРАЛА ОН СИДИТ ПОД ЕБАНЫМ НАХУЙ ГИГАНТСКИМ ПОДСОЛНУХОМ ГДЕ ТЫ ВООБЩЕ НАШЕЛ ТАКОЙ ЗДОРОВЫЙ ПОДСОЛНУХ СУКА

Ну, заяц, погоди ПИДОРАС ШЕРСТЯНОЙ 20 СЕРИЙ ЗА ТОБОЙ ГОНЯЮСЬ НАХУЙ ВООБЩЕ МНЕ НУЖЕН ЗАЯЦ У НАС ЖЕ РАЗВИТАЯ ИНФРАСТРУКТУРА Я МОГУ КУПИТЬ ВСЕ ЧТО МНЕ НУЖНО А ВМЕСТО ЭТОГО БЕГАЮ ЗА ТОБОЙ КАК ТУПОЕ ЖИВОТНОЕ

Я на солнышке лежу КАК СРАНЫЙ ГЕДОНИСТ ВЪЕБЫВАЙТЕ ДАЛЬШЕ НА СВОИХ ПРЕДПРИЯТИЯХ МНЕ ПОХУЙ Я БУДУ ПОТРЕБЛЯТЬ РЕЗУЛЬТАТЫ ВАШЕГО ТРУДА ФАК ЙЕА, КАПИТАЛИЗМ 

Хорошо живет на свете Винни Пух ПОТОМУ ЧТО ОН СУКА МЕДВЕДЬ СПИТ ПОЛГОДА РАЗОРЯЕТ УЛЬИ НАПАДАЕТ НА НЕОСТОРОЖНЫХ ТУРИСТОВ ВХОДЫ В ЖИЛИЩЕ РАСХУЯРИВАЕТ СВОИМ ЖИРНЫМ ПЕРДАЛИЩЕМ

Друзья, давайте жить дружно А ИНАЧЕ ВАШ ПЕРДАК УКРАСИТ МОЮ СТЕНКУ ТРОФЕЕВ Я БЫ НА ВАШЕМ МЕСТЕ ДЕСЯТЬ РАЗ ПОДУМАЛ ПРЕЖДЕ ЧЕМ СВЯЗЫВАТЬСЯ С ГОВОРЯЩИМ НЕЕСТЕСТВЕННО МИРОЛЮБИВЫМ КОТОМ ВОЗМОЖНО У МЕНЯ БИПОЛЯРНОЕ РАСТРОЙСТВО А ШКАФ ЗАБИТ ТРУПАМИ МЫШЕЙ ХОТЯ ЭТО БЫЛО БЫ ВПОЛНЕ ЕСТЕСТВЕННО Я ВЕДЬ КОТ

Ничего на свете лучше нету, чем бродить друзьям по белу свету ВОРОВАТЬ УБИВАТЬ НАСИЛОВАТЬ БЕЛОКУРЫХ ЖЕНЩИН УСЫПИВ ИХ БДИТЕЛЬНОСТЬ НА СКОРУЮ РУКУ ПРИДУМАННОЙ ПОП МУЗЫКОЙ ИСПОЛНЕННОЙ ГОВОРЯЩИМИ ЖИВОТНЫМИ

Я играю на гармошке
У прохожих на виду...
К сожаленью СУКА КРИЗИС ЕБАНЫЙ ВЫГНАЛИ С РАБОТЫ, ДОЛЖНОСТИ МЕНЕДЖЕРА, УШЛА ЖЕНА, КРЕДИТ ЗА МАШИНУ НАДО КАК-ТО ОТДАВАТЬ, МНЕ ПОХУЙ, ДАВАЙ МЕЛОЧЬ И УЁБЫВАЙ ДАЛЬШЕ УЧИТСЯ НА ТАКУЮ ЖЕ НЕ НУЖНУЮ СПЕЦИАЛЬНОСТЬ, ЧТОБЫ ЗАМЕНИТЬ МЕНЯ НА ЭТОМ МЕСТЕ, КОГДА Я ПОДОХНУ ОТ ЦИРРОЗА ПЕЧЕНИ

Чай на столе, сухари и сушки. А ГДЕ НОРМАЛЬНАЯ ЕДА БЛЯДЬ ГДЕ МЯСО СУП ДА ЧТО УГОДНО МУЖИК С РАБОТЫ ПРИШЕЛ НИХУЯ ВЕСЬ ДЕНЬ НЕ ЖРАЛ А ТЫ СО СВОИМ ЧАЕМ ДА УЕБИСЬ ТЫ ОБ СТОЛ НА ХУЮ Я ВЕРТЕЛ ТВОИ СУШКИ НА ТЕБЕ В ТАБЛО МРАЗЬ ЛЕНИВАЯ ДЕТИ ПЛАЧУТ ПОСУДА РАСКИДАНА ОПЯТЬ ПРИДЕТСЯ ПЕЛЬМЕНИ СЕБЕ ВАРИТЬ ПОУЖИНАЛИ БЛЯДЬ В КРУГУ СЕМЬИ

Птица счастья завтрашнего дня, прилетела крыльями звеня И НАСРАЛА СУКА ОГРОМНУЮ КУЧУ ГОВНА ЗАЕБАЛСЯ УБИРАТЬ И ТАК В ГОВНЕ ЖИВЁМ МАТЬ НА ТРЁХ РАБОТАХ ОТЕЦ АЛКОГОЛИК ТРОЕ МАЛЕНЬКИХ ДЕТЕЙ А ТУТ ЕЩЁ ПТИЦА ЕБУЧАЯ ГДЕ ЖЕ СЧАСТЬЕ-ТО БЛЯДЬ

Чип Чип Чип Чип и Дейл ПРОСТО БУРУНДУКИ ОНИ НЕ ПРИДУТ К ТЕБЕ НА ПОМОЩЬ ТЫ И ДАЛЬШЕ БУДЕШЬ ЖИТЬ В ЭТОМ ГАДКОМ МИРЕ ПОЛНОМ ЖЕСТОКОСТИ И ПРЕДАТЕЛЬСТВА ТЫ САМ ГНИЕШЬ ИЗНУТРИ ДРОЧАЩИЙ НА ГАЕЧКУ УЕБОК

Жили у бабуси два весёлых гуся ЕБУТСЯ ДРУГ С ДРУГОМ ЦЕЛЫЙ ДЕНЬ СУКИ ГУСЯТ НЕТ БАБКА В ГОВНЕ УМИРАЕТ ОТ ГОЛОДА А ТУТ ВОЙНА НЕМЦЫ РАЗРУХА СОЛДАТЫ ЗАБРАЛИ ПОСЛЕДНЕЕ ВСЮ ДЕРЕВНЮ РАСХУЯРИЛИ БАБКУ ИЗНАСИЛОВАЛИ ВОТ ТАКИЕ ВОТ У НЕЁ ГУСИ ЁБАНЫЙ В РОТ

Тук-тук, кто в теремочке живет? ОТКРЫВАЙ БЫСТРА БЛЯДЬ ОМОН СУКА ПРИЕХАЛ ВАШ ТЕРЕМОК И ВСЁ ИМУЩЕСТВО КОНФИСКУЮТ ЗА ВАШИ ДОЛГИ ПИДОРЫ КРЕДИТОВ БЛЯДЬ ПОНАБРАЛИ ХУЕПЛЁТЫ И НЕ ОТДАЮТ ПОТОМУ ЧТО ТУПЫЕ ЖИВОТНЫЕ

Арабская ночь, волшебный Восток СУКА ВЕЗДЕ ПЕСОК В ЖОПЕ ПЕСОК В ШТАНАХ ПЕСОК ПРИХОДИТСЯ НОСИТЬ ГИГАНТСКИЕ ГАЛИФЕ ЧТОБЫ ПЕРДАК НЕ ПОТЕЛ НИЩЕТА ДИКИЕ НРАВЫ УЩЕМЛЕНИЕ ПРАВ ЖЕНЩИН НАРОД ЖИВЕТ В ГОВНЕ ЗАТО У СУЛТАНА ГОРЫ ЗОЛОТА В СРАНОМ ДВОРЦЕ ЕБАНАЯ ТЕОКРАТИЯ

Жил да был чёрный кот за углом. И кота ненавидел весь дом. Только песня совсем не о том ОНА О ТОМ КАК ОН ХОТЕЛ ВЫЕБАТЬ КОШКУ НО ЕГО ПИЗДИЛИ ПО ХАРДКОРУ И ОБЪЯСНЯЛИ ЧТО ЧЕРНЫХ ТУТ НЕ ЛЮБЯТ

Утки! Ууу! Тайных кладов миллионы НИКТО НЕ ХОЧЕТ РАБОТАТЬ ВСЕ ХОТЯТ ВСЕ И СРАЗУ ЛЕНИВЫЕ ТВАРИ ПРЕНЕБРЕГАЮЩИЕ ШТАНАМИ УТКИ СКРУДЖ ХРАНИТ ГИГАНТСКИЕ ОБЪЕМЫ ДЕНЕГ НАЛИЧНЫМИ И ЭТОМУ БУРЖУА ВСЕ МАЛО ЗАСТАВЛЯЕТ РОДСТВЕННИКОВ РИСКОВАТЬ ЖИЗНЬЮ И НЕ ДАЕТ ИМ ВЗАМЕН НИЧЕГО

Сюрприз, да здравствует сюрприз ОХУЕТЬ СЮРПРИЗ ДЛЯ ЧЕЛОВЕКА СО СТРИЖКОЙ ТРЕУГОЛЬНИКОМ НЕ МОЖЕТ В ЖИЗНИ БОЛЬШЕ БЫТЬ НИКАКИХ НЕОЖИДАННОСТЕЙ КАКАЯ У НЕГО ВООБЩЕ РОЛЬ В ИХ ОТЛАЖЕННОМ СОЦИУМЕ ОН НИХУЯ НЕ УМЕЕТ КРОМЕ КАК ЗАПРАВЛЯТЬ УЖАСНУЮ ОРАНЖЕВУЮ РУБАХУ В ШТАНЫ

Ты морячка, я моряк! Ты рыбачка, я рыбак! МЫ МОГЛИ БЫ СТАТЬ ИДЕАЛЬНОЙ ПАРОЙ РОДИТЬ КРАСИВЫХ ДЕТЕЙ ЖИТЬ СЧАСТЛИВО ВЕДЬ МЫ ТАК ПОДХОДИМ ДРУГ ДРУГУ НО ТЫ МРАЗЬ ЕБУЧАЯ ВИДИШЬ ВО МНЕ ТОЛЬКО ДРУГА Я ЖЕЛАЮ ТЕБЕ ВЕЧНЫХ МУЧЕНИЙ ТВАРЮГА ЕБЛИВАЯ ПУСТЬ ТВОИ ДЕТИ РОДЯТСЯ МЁРТВЫМИ ПУСТЬ ТВОИХ РОДСТВЕННИКОВ РАСПИДОРАСИТ ОТ УЖАСА БЫТИЯ

В каждом маленьком ребёнке и в мальчишке, и в девчонке! ЁБАНЫЕ ПРОЖОРЛИВЫЕ ТВАРИ НАХУЯ ВАС РОЖАТЬ ВЫ БЕСПОЛЕЗНОЕ ГОВНО КОТОРОЕ ВЫРАСТАЕТ И ПОСЫЛАЕТ РОДИТЕЛЕЙ НАХУЙ 

Не надо печалиться, вся жизнь ПРОЁБАНА НАХУЙ БЛЯТЬ ЛУЧШЕ БЫ УДАВИЛСЯ В ПИЗДУ МЕРЗОПАКАСТНАЯ РАБОТА ДОМ КРЕДИТ ЖЕНЩИНЫ НЕ ДАЮТ А У МЕНЯ КОРОТКИЙ СТВОЛ И ХУЙ ЗНАЕТ ЧО ТЕПЕРЬ ДЕЛАТЬ

крошка сын к отцу пришел и спросила кроха ЕСТЬ ПАЛТОСИК ДО ЗАВТРА ТРУБЫ ГОРЯТ БЕЗПЕЗДЫ ВОТ ТЕ КРЕСТЬ ЖИВООТВОРЯЩИЙ БАТЮШКА ИНОКЕНТИЙ


нажми на кнопку получишь результат СУКА БЛЯТЬ ХУЛИ МОЮ АППАРАТУРУ ЛОМАЕШЬ ТВАРЮГА ЕБУЧАЯ БУДЕШЬ НОВУЮ ПОКУПАТЬ

Ведь я не Ангел, но я хочу быть с тобой ДА ПОШЛА ТЫ НАХУЙ ШЛЮХА СИФИЛИСНАЯ Я ТЕБЯ НЕНАВИЖУ ТВАРЬ НАДО БЫЛО ДЕСЯТЬ ЛЕТ НАЗАД ДА СКАЗАТЬ В ОДИННАДЦАТОМ КЛАССЕ А СЕЙЧАС ИДИ НАХУЙ К СВОЕМУ ЕБАРЮ АЛКАШУ И ТВОИМ ДАУНАМ ДЕТЯМ ЕБАНАЯ ТЫ МРАЗЬ

Добрый доктор Айболит, он под деревом сидит. И ТОРГУЕТ СУКА НЕЛЕГАЛЬНО СИЛЬНОДЕЙСТВУЮЩИМИ ПРЕПАРАТАМИ ТРАМАДОМ ФЕНОБАРБИТАЛ СИДНОКАРБ АМФЕТАМИН ЗВЕРИ В ЛОМКАХ ВЫНОСЯТ ПОСЛЕДНЕЕ ИЗ ДОМА МУСОРА НАБИГАЮТ ДУБИНКАМИ ОТХУЯЧИЛИ ПОЧКИ ОТБИЛИ СУД ПРИГОВОР ПЯТНАХА ОПУСТИЛИ ОЧКО ПОРВАЛИ СИДИТ АЙБОЛИТ НА ПАРАШЕ КУКАРЕКАЕТ

Полночь уже, и почти никого Я знаю точно - придёт, ожидаю его. ДА ПОШЛА ТЫ НАХУЙ ШЛЮХА Я ЛУЧШЕ ДОМА ЗА ЧАЙКОМ КАПЧУ ПОНУЛЬЧУЮ ЧЕМ ОПЯТЬ С ТОБОЙ НА БЛЯДСКИЕ ТЕМЫ РАЗГОВАРИВАТЬ ТОЖЕ БЛЯТЬ ДРУГА НАШЛА

Карусель, карусель НЕ БЫЛА ЗАКРЕПЛЕНА РАСКРУТИЛАСЬ ОТОРВАЛАСЬ ПОКАТИЛАСЬ ТРУПЫ ТРУПЫ ТРУПЫ ТРУПЫ ДЕТЕЙ ПОВСЮДУ КРОВЬ БРЫЗЖЕТ ВО ВСЕ СТОРОНЫ ДЕТСКИЕ КРИКИ УЖАСА КИШКИ НАМОТАЛИСЬ ГОЛУБИ КЛЮЮТ ПЕЧЕНЬ ПИЗДЕЦ БЛЯДЬПИЗДЕЦ

А мы не ангелы, парень, нет, мы БИТАРДЫ БЛЯДЬ ТРОЛЛИ ЛЖЕЦЫ ДЕВСТВЕННИКИ ПОЗОР СЕМЬИ СИДИМ В ПОДВАЛЕ ПРОСИРАЕМ РОДИТЕЛЬСКИЕ ДЕНЬГИ ЖИЗНИ НЕТ МЕСЯЦАМИ НА УЛИЦЕ НЕ ПОЯВЛЯЕМСЯ ПРЫЩИ НА ВСЁ ЕБАЛО ЖИЗНЬ ПРОЁБАНА ПИЗДЕЦ ЛОЖИТЬСЯ И ПОДЫХАТЬ

В банаво-лимонном Сингапуре ДИНАМИЧНО РАЗВИВАЮЩАЯСЯ ЭКОНОМИКА БЛАГОПРИЯТНЫЙ ИНВЕСТИЦИОННЫЙ КЛИМАТ ВЫСОКОКОНКУРЕНТНАЯ СРЕДА ВЫСОКООБРАЗОВАННОЕ И ДИСЦИПЛИНИРОВАННОЕ НАСЕЛЕНИЕ БЛАГОСОСТОЯНИЕ ТОЧНАЯ ЭЛЕКТРОНИКА НАРОД СЧАСТЛИВ ВСЕ ЗАШИБИСЬ НЕ ТОЧНО У НАС В БЕЛАРУСИ ВСЕ В СРАНОМ ГОВНЕ БАЦЬКА ОХУЕЛ СКОРО НА БАРРИКАДЫ ПОЙДЕМ

Маленькой елочке холодно зимой, маленькую елочку СРУБИЛИ ЧУРКИ, ДВА СТАРЫХ ПИДАРАСА ПРИШЛИ И РАЗЬЕБАШИЛИ НАХЕР ЕЛОЧКУ СУКИ! ПРОДАЮТ ПО 100 РУБЛЕЙ НА РЫНКЕ! СМОЛА, КОРА, ОПИЛКИ РАСПИДОРАСИЛО И ДРЕВЕСИНОЙ ЗАПАХЛО БЛЯДЬ!
* Говно
** Вместилище души человека                                 :поток_сознания:
Гавно, когда свежее, очень теплое. Оно хранит ту частичку тепла хозяина еще долго. Не теплоту ли мы ценим в людях? Гавно искреннее. Оно воняет всегда, как говно и никогда, как пироженное. Вы никогда не спутаете гавно ни с чем. Да оно и не стремиться вас ввести в заблуждение. Гавно не предаст вас, говно останеться всегда вашим гавном и никогда не переметнется к врагам. Не задумывались ли вы, что гавно - это вместилище души человека? Задумайтесь.
** Невидимое говно                                                    :epic:
Самое страшное, что можно представить — это НЕВИДИМОЕ ГОВНО. Если оно появится, то миру конец!!! Подумайте сами… Идёшь по улице — чисто, наступил в невидимое говно, пришёл на работу и воняешь, а его не видно и не понятно откуда пахнет. Все думают, что вот млядь обосрался ты. А ты стремаешься, озираешься, подошвы рассматриваешь, ощупываешь себя — вот и руки уже в невидимом говне. Так весь перемажешься, и под ногтями застрянет, и всю клавиатуру перемажешь, и мышку. Всё в говне, воняет, а чисто и аккуратно. Из-за такого дела происходит срыв работы. Едешь домой, а там уже все поручни в метро в говне (не только же ты наступил в невидимое говно), вонь страшная, некоторые уже блюют… Не пожрать — руки в говне, мыть без толку — краны в говне и ручки дверные… Ужас и кошмар!!! Крах и апокалипсис!!!
* <enter category name here>
** Джедаи — сборище лицемерных ублюдков
Джедаи сборище лицемерных ублюдков которые вообразили себя буддистами. Они боятся, что ситы придут к власти, но не от того что ситы это воплощение зла, а лишь потому, что не хотят терять свою власть, ибо их жопа в тепле. Все это они прикрывают своим кодексом, следовать которому, значит быть куклой. Их кодекс в открытую призывает отказаться от всего человеческого, от чувств, эмоций, любви и ненависти, всего того что делает тебя живым. Джедаи столетиями мародёрствовали в гробницах Тёмных Лордов, собирая все документы, манускрипты, артефакты и голокроны, только из страха перед могучими ситами, они боятся свержения, неминуемого свержения, если вдруг ситы вновь восстанут из своих могил и голокронов, в лицах молодых джедаев, случайно нашедших голокрон или артефакт и польстившихся на настоящую силу и могущество – темную сторону силы. Джедаи действуют как отчаявшиеся трусы, посылая сотнями джедаев и падаванов на войну, надеясь побороть числом. Тут не нужна военная стратегия, мастерство ведения войны, просто знать место противника и делать раш пушечным мясом, в то время как верхушка в лице магистров отсиживается на Корусканте. Они в любое время могут набрать новых юнлингов, отобрав совсем юных детей у их родителей и разумеется, родители больше никогда не увидят свое чадо, ведь через 20 лет Йода со своей пиздобратией снова пошлют его в какую-нибудь мясорубку. 

Ситы же, пытаются построить империю, не жалкое подобие демократии основанной на лжи и лицемерии, а настоящую империю, с собственной армией, которая готова погибнуть за эту империю. Армия клонов, дроидов, но никак не рядовых людей и их детей. У ситов есть эмоции, как бы странно это не звучало, они более человечны, они не отплевываются от инстинктов, от человеческого естества, они раскрывают силу с помощью этого естества. Силу, которая джедаям и не снилась. Дарт Бейн одними лишь хитростью и умом, уничтожил сотню джедаев и всё лживое, джедаеподобное братство ситов, основанного Кааном, который пренебрег уже тогда существовавшим, хоть и негласно правилу двух. Правило которое негласно существовало со времен Дарта Ревана. «Отныне их будет только двое. Учитель и Ученик. Не больше и не меньше. Один— чтобы воплощать могущество, другой— чтобы постигать его.» 

Идеальное решение, до которого ограниченные умом джедаи не смогли дойти сами. На протяжении тысячи лет ученик набирался опыта у учителя, превосходил его в мастерстве, убивал учителя. Тысячу лет, могущество ситов росло с огромной силой, ведь каждый учитель, сильнее предыдущего. Они разрабатывали хитрейшие долгосрочные планы, делали поправки на постоянно меняющуюся ситуацию в республике, имели шпионов и доносчиков везде где их можно было иметь. В наглую, открыто, маскировавшись под джедая уносили информацию прямо из джедайского храма на Корусанте, слепцы джедаи этого даже не замечали. Во что же все это вылилось? Темный Владыка на посту Канцлера, под носом джедаев и от лица джедаев была создана армия клонов, которую джедаи посчитали своей. Под их же носом была создана «Звезда Смерти», огромный космический корабль, который способен уебать планету за несколько секунд. Дарт Сидиус одним лишь приказом, убил абсолютно всех джедаев, кроме двух. Один из них, самый сильный, Магистр Йода, эпично проебал Дарту Сидиусу и с клеймом позора отправился в изгнание, где и сдох от старости. Бен Кеноби же, просто был убит от руки Вейдера, своего бывшего ученика. Ученик превзошел своего учителя, правило двух в действии. 

Вывод: ситы умные, могущественные и дальновидные, с правильными империалистическими планами на республику, джедаи же в свою очередь, трусливые отщепенцы, готовые на все лишь бы не проебать свое место у власти, прикрывая свою задницу лживой демократией.

* Баттхёрт как он есть
** Грамотный чеченец
:PROPERTIES:
:bhlevel: 8
:END:
Охуеть как смешно, педик.
Ты думаешь это шутка, да? Думаешь, что нагрубить мне это хорошая идея? Я же убью тебя, нахуй.
Да, пошутить надо мной это так весело, так весело, что я забыл засмеяться.
Если ты хочешь говорить со мной таким тоном, то почему бы нам не встретиться и не сказать мне всё в лицо, чтобы я ответил на пиздёж ударом кулака по твоему носу.
Конечно, ты можешь много чего наговорить сидя за сотни километров, но спорю, что будь мои кулаки рядом с твоей рожей, ты стал бы похож на телевизор, который работает без звука и кнопки громкости не работают. Поэтому сделай себе одолжение - заткнись блять, если не хочешь сдохнуть.
И когда захочешь написать мне ещё нечто подобное, я хочу, чтобы ты запомнил следущее.
Я знаю человека, который создал google maps и найти тебя мне не составит труда. Хочешь ещё проблем?...
Я так не думаю, пидор.
Ты вообще представляешь себе, что такое Боевое Самбо? Я да, я Чеченец, служивший в ВДВ и идеально им владею.
И применю на тебе все его приёмы, хуйло блять. Ты представляешь в какой опасности будешь находиться,если я найду тебя?
Я на сто баксов серьёзен.
Пиздец, я не намерен терпеть очередного ньюфага-лузера. У меня хотя бы есть девушки, с которыми я сегодня опять занимался сексом в отличии от тебя - девственного куска непатриотичного ГОВНА.
